package jop.ddr2

import spinal.core._

/**
 * BlackBox for the Altera ALTMEMPHY DDR2 High Performance Controller as
 * generated for the A-E115FB board (EP4CE115 + 1 GB DDR2 SODIMM).
 *
 * HALF-RATE variation: the local interface is 256 bits wide at 83 MHz, rather
 * than 128 bits at 166 MHz. Regenerated from the vendor's full-rate original
 * because 166 MHz is well above JOP's fmax on this -7 part, and because a
 * 256-bit local word matches both the DDR2 BL=4 burst (32 bytes) and the cache
 * line width we want. See docs/boards/ae115fb-ddr2-bringup.md.
 *
 * The port list matches the generated `ddr2_64bit.v`. The IP is regenerated from
 * a checked-in variation file by `make ip` — the generated output is ~3.7 MB and
 * is derived, so only the variation is under version control. Regeneration needs
 * Quartus 18.1: Intel dropped Cyclone IV DDR2 ALTMEMPHY after that.
 *
 * Local interface notes, versus the Xilinx MIG we already drive:
 *  - ONE `local_ready` covers both the command and its write data; MIG splits
 *    those into app_rdy and app_wdf_rdy.
 *  - `local_wdata` is accepted on the same cycle as `local_write_req`; there is
 *    no separate write-data handshake.
 *  - User logic runs on `phy_clk`, an OUTPUT of the controller — 83 MHz for this
 *    half-rate variation, so the whole datapath lives in that domain.
 *  - `local_address` counts 256-bit words: 2^25 * 32 bytes = 1 GB.
 *  - Nothing may be issued until `local_init_done` — calibration takes a while
 *    after reset.
 */
class Ddr2BlackBox extends BlackBox {
  setDefinitionName("ddr2_64bit")

  val io = new Bundle {
    // --- controller local (user) interface ---
    val local_address     = in Bits (25 bits)   // 256-bit word address -> 1 GB
    val local_write_req   = in Bool()
    val local_read_req    = in Bool()
    val local_burstbegin  = in Bool()
    val local_wdata       = in Bits (256 bits)
    val local_be          = in Bits (32 bits)   // byte enables, active high
    val local_size        = in Bits (3 bits)    // burst length in local words
    val local_ready       = out Bool()          // command AND write data accepted
    val local_rdata       = out Bits (256 bits)
    val local_rdata_valid = out Bool()
    val local_refresh_ack = out Bool()
    val local_init_done   = out Bool()          // calibration complete

    // --- clocking / reset ---
    val pll_ref_clk       = in Bool()
    val global_reset_n    = in Bool()
    val soft_reset_n      = in Bool()
    val phy_clk           = out Bool()          // user clock domain
    val aux_full_rate_clk = out Bool()
    val aux_half_rate_clk = out Bool()
    val reset_phy_clk_n   = out Bool()          // reset, synchronous to phy_clk
    val reset_request_n   = out Bool()

    // --- DDR2 device pins ---
    val mem_odt   = out Bits (2 bits)
    val mem_cs_n  = out Bits (2 bits)
    val mem_cke   = out Bits (2 bits)
    val mem_addr  = out Bits (14 bits)
    val mem_ba    = out Bits (2 bits)
    val mem_ras_n = out Bool()
    val mem_cas_n = out Bool()
    val mem_we_n  = out Bool()
    val mem_dm    = out Bits (8 bits)
    val mem_clk   = inout(Analog(Bits(2 bits)))
    val mem_clk_n = inout(Analog(Bits(2 bits)))
    val mem_dq    = inout(Analog(Bits(64 bits)))
    val mem_dqs   = inout(Analog(Bits(8 bits)))
  }

  noIoPrefix()

  // phy_clk is generated by the IP and clocks everything downstream of it; the
  // BlackBox itself is driven by pll_ref_clk, so no SpinalHDL clock domain is
  // mapped onto this component.
}
