package jop.config

/**
 * Quartus .qsf Pin Assignment Generator
 *
 * Generates set_location_assignment lines from JopConfig.
 * Combines:
 *   - Infrastructure pins (clock, LEDs, SDRAM clock)
 *   - SDRAM memory pins (from BoardDevice mapping)
 *   - DeviceDriver pins (UART, Ethernet, VGA, SD)
 *
 * Resolution chain:
 *   DeviceDriver.pins: verilogPort -> deviceSignal
 *   BoardDevice.mapping: deviceSignal -> connectorRef
 *   SystemAssembly.resolvePin: connectorRef -> fpgaPin
 */
object QsfGenerator {

  case class PinAssignment(fpgaPin: String, verilogPort: String)

  /** Generate all pin assignments for a JopConfig */
  def pinAssignments(config: JopConfig): Seq[PinAssignment] = {
    val assembly = config.assembly
    val sys = config.system

    val infra = infrastructurePins(assembly)
    val sdram = sdramPins(assembly, sys)
    val drivers = driverPins(assembly, sys)

    infra ++ sdram ++ drivers
  }

  /** Infrastructure: clock, SDRAM clock output, LEDs — discovered from assembly */
  private def infrastructurePins(assembly: SystemAssembly): Seq[PinAssignment] = {
    // Clock: find any CLOCK_* device
    val clock = assembly.allDevices
      .find(_.part.startsWith("CLOCK_"))
      .flatMap(d => assembly.pinMapping(d.part).get("clock"))
      .map(PinAssignment(_, "clk_in"))
      .toSeq

    // SDRAM clock: from SDR SDRAM device (DDR3 clock is managed by MIG IP)
    val sdramClk = assembly.memoryDevices
      .filter(_._2.memType == MemoryType.SDRAM_SDR)
      .headOption
      .flatMap { case (bd, _) => assembly.pinMapping(bd.part).get("CLK") }
      .map(PinAssignment(_, "sdram_clk"))
      .toSeq

    // LEDs: collect from all LED devices across boards, preserve numbering
    val ledMappings = assembly.allPinMappings("LED")
    val leds = ledMappings.toSeq
      .sortBy { case (signal, _) => signal.stripPrefix("led").toInt }
      .map { case (signal, fpgaPin) =>
        PinAssignment(fpgaPin, s"led[${signal.stripPrefix("led")}]")
      }

    clock ++ sdramClk ++ leds
  }

  /** SDR SDRAM pins from memory device's BoardDevice mapping */
  private def sdramPins(assembly: SystemAssembly, sys: JopSystem): Seq[PinAssignment] = {
    // Find SDR SDRAM device on the assembly
    val sdramDevices = assembly.memoryDevices.filter(_._2.memType == MemoryType.SDRAM_SDR)
    sdramDevices.headOption match {
      case Some((bd, md)) =>
        val devicePins = assembly.pinMapping(md.name)
        DeviceDriver.sdramPins.flatMap { case (verilogPort, deviceSignal) =>
          devicePins.get(deviceSignal).map(PinAssignment(_, verilogPort))
        }.toSeq
      case None => Seq.empty  // DDR3 pins managed by MIG IP, not in .qsf
    }
  }

  /** Driver pins from system's configured drivers */
  private def driverPins(assembly: SystemAssembly, sys: JopSystem): Seq[PinAssignment] = {
    sys.drivers.flatMap { driver =>
      val devicePins = assembly.pinMapping(driver.devicePart)
      driver.pins.flatMap { case (verilogPort, deviceSignal) =>
        devicePins.get(deviceSignal).map(PinAssignment(_, verilogPort))
      }
    }
  }

  /** Format pin assignments as Quartus TCL */
  def toQsf(assignments: Seq[PinAssignment]): String = {
    assignments.map { a =>
      s"set_location_assignment ${a.fpgaPin} -to ${a.verilogPort}"
    }.mkString("\n")
  }

  /** Generate global assignments (FAMILY, DEVICE, TOP_LEVEL_ENTITY) */
  def globalAssignments(config: JopConfig): String = {
    val fpga = config.fpga
    val family = fpga.family match {
      case FpgaFamily.CycloneIV => "Cyclone IV GX"
      case FpgaFamily.CycloneV  => "Cyclone V"
      case FpgaFamily.MAX10     => "MAX 10"
      case FpgaFamily.Artix7    => "Artix-7"
      case FpgaFamily.ECP5      => "ECP5"
    }
    val entity = if (config.system.cpuCnt >= 2) "JopSmpSdramTop" else "JopSdramTop"
    Seq(
      s"""set_global_assignment -name FAMILY "$family"""",
      s"set_global_assignment -name DEVICE ${fpga.name}",
      s"set_global_assignment -name TOP_LEVEL_ENTITY $entity",
      """set_global_assignment -name STRATIX_DEVICE_IO_STANDARD "3.3-V LVCMOS""""
    ).mkString("\n")
  }

  /** Generate complete pin assignment section */
  def generate(config: JopConfig): String = {
    val assignments = pinAssignments(config)
    val globals = globalAssignments(config)

    val sb = new StringBuilder
    sb.append("# Generated by JOP QsfGenerator\n")
    sb.append("# Assembly: ").append(config.assembly.name).append("\n")
    sb.append("# System: ").append(config.system.name).append("\n\n")

    sb.append("# Global assignments\n")
    sb.append(globals).append("\n\n")

    sb.append("# Pin assignments\n")
    sb.append(toQsf(assignments)).append("\n")

    sb.toString
  }
}

/** Print generated QSF for EP4CGX150 preset */
object QsfGeneratorMain extends App {
  val config = if (args.contains("--dbfpga"))
    JopConfig.ep4cgx150Serial.copy(systems = Seq(
      JopConfig.ep4cgx150Serial.system.copy(
        drivers = Seq(DeviceDriver.Uart, DeviceDriver.EthGmii,
                      DeviceDriver.SdNative, DeviceDriver.VgaDma))))
  else
    JopConfig.ep4cgx150Serial

  println(QsfGenerator.generate(config))
}
