package jop.pipeline

import spinal.core._
import jop.{JumpTableData, JumpTableSource}

/**
 * Jump Table Init Data - microcode-layout-specific addresses and entries.
 *
 * Holds the 256-entry jump table plus special handler addresses.
 * All ROMs are supersets containing ALL hardware handlers.
 * Use resolveJumpTable() in JopCoreConfig to patch unwanted bytecodes to sys_noim.
 */
case class JumpTableInitData(
  entries:     Seq[BigInt],
  sysNoimAddr: Int,
  sysIntAddr:  Int,
  sysExcAddr:  Int,
  altEntries:  Map[Int, Int] = Map.empty,
  dspAltEntries: Map[Int, Int] = Map.empty
) {
  /** Patch specific bytecodes to sys_noim, making their HW handlers unreachable (dead code in ROM). */
  def disable(bytecodes: Int*): JumpTableInitData =
    copy(entries = entries.zipWithIndex.map { case (addr, i) =>
      if (bytecodes.contains(i)) BigInt(sysNoimAddr) else addr
    })

  /** Patch a bytecode to its alternate (software) handler address. */
  def useAlt(bytecode: Int): JumpTableInitData =
    altEntries.get(bytecode) match {
      case Some(altAddr) => copy(entries = entries.updated(bytecode, BigInt(altAddr)))
      case None => this  // no alternate available, keep default
    }

  /** Patch a bytecode to its DSP-accelerated handler address. */
  def useDspAlt(bytecode: Int): JumpTableInitData =
    dspAltEntries.get(bytecode) match {
      case Some(dspAddr) => copy(entries = entries.updated(bytecode, BigInt(dspAddr)))
      case None => this  // no DSP alternate available, keep default
    }
}

object JumpTableInitData {
  /** Create from any Jopa-generated jump table object */
  private def from(src: JumpTableSource): JumpTableInitData =
    JumpTableInitData(src.entries, src.sysNoimAddr, src.sysIntAddr, src.sysExcAddr, src.altEntries, src.dspAltEntries)

  /** SIMULATION superset ROM (all HW handlers: IntegerCU + FloatCU) */
  def simulation: JumpTableInitData = from(JumpTableData)

  /** SERIAL-boot superset ROM (all HW handlers: IntegerCU + FloatCU) */
  def serial: JumpTableInitData = from(jop.SerialJumpTableData)

  /** FLASH-boot superset ROM */
  def flash: JumpTableInitData = from(jop.FlashJumpTableData)

  // Bare variants removed — superset ROM contains both HW and SW handlers.
  // Use resolveJumpTable() with imul: Microcode to select software multiply.
}

/**
 * Jump Table Configuration
 *
 * Configures the jump table parameters for bytecode-to-microcode address translation.
 *
 * @param pcWidth  Address bits of microcode ROM (default: 11 bits = 2K instructions)
 * @param initData Jump table init data (default: simulation microcode)
 */
case class JumpTableConfig(
  pcWidth:  Int              = 11,
  initData: JumpTableInitData = JumpTableInitData.simulation
) {
  require(pcWidth > 0, "PC width must be positive")
  require(pcWidth <= 16, "PC width too large (max 16 bits)")

  /** Number of bytecode entries (always 256 for Java bytecode) */
  def entries: Int = 256
}

/**
 * Jump Table - Java Bytecode to Microcode Address Translation
 *
 * Translates 8-bit Java bytecode opcodes to microcode ROM addresses.
 * Uses ROM-based lookup with data generated by Jopa assembler.
 *
 * @param config Jump table configuration
 */
case class JumpTable(
  config: JumpTableConfig = JumpTableConfig()
) extends Component {

  val io = new Bundle {
    val bytecode = in Bits(8 bits)              // Java bytecode opcode (0x00-0xFF)
    val jpaddr   = out UInt(config.pcWidth bits) // Microcode ROM address

    // Interrupt/exception priority muxing (Phase E)
    val intPend = in Bool()                     // Interrupt pending
    val excPend = in Bool()                     // Exception pending
  }

  // ROM stores microcode addresses (256 entries, one per bytecode)
  val rom = Mem(UInt(config.pcWidth bits), config.entries)

  // Initialize from provided jump table data
  rom.init(config.initData.entries.map(addr => U(addr.toInt, config.pcWidth bits)))

  // Asynchronous ROM read (combinational, 0-cycle latency)
  val normalAddr = rom.readAsync(io.bytecode.asUInt)

  // Priority muxing: Exception > Interrupt > Normal bytecode
  when(io.excPend) {
    io.jpaddr := U(config.initData.sysExcAddr, config.pcWidth bits)
  }.elsewhen(io.intPend) {
    io.jpaddr := U(config.initData.sysIntAddr, config.pcWidth bits)
  }.otherwise {
    io.jpaddr := normalAddr
  }

  // Verification helpers (disabled in synthesis)
  if (GenerationFlags.simulation) {
    assert(
      assertion = io.bytecode.asUInt < config.entries,
      message = "Invalid bytecode out of range",
      severity = WARNING
    )
    assert(
      assertion = io.jpaddr < (1 << config.pcWidth),
      message = "Jump address out of microcode ROM range",
      severity = WARNING
    )
  }
}

object JumpTable {

  object SpecialAddr {
    val SYS_NOIM = JumpTableData.sysNoimAddr
    val SYS_INT  = JumpTableData.sysIntAddr
    val SYS_EXC  = JumpTableData.sysExcAddr
  }

  def getAddress(bytecode: Int): Int = {
    require(bytecode >= 0 && bytecode < 256, "Bytecode out of range")
    JumpTableData.entries(bytecode).toInt
  }

  def main(args: Array[String]): Unit = {
    SpinalConfig(
      mode = Verilog,
      targetDirectory = "core/spinalhdl/generated"
    ).generate(JumpTable())
  }
}
