# Ethernet (RTL8211EG) and SD-card pin assignments for the QMTECH Wukong.
#
# These are BOARD pins, so they are the same whatever main memory a config uses.
# They lived only in wukong_ddr3.xdc, which meant wukongSdrFull — SDR plus
# Ethernet plus SD — could not generate a bitstream at all: 32 of 77 ports had
# no LOC or IOSTANDARD and write_bitstream refused with DRC NSTD-1 / UCIO-1.
#
# Extracted here so the SDR flow can read them too. wukong_ddr3.xdc still holds
# its own copy: removing them from a constraint file that six verified DDR3
# configs depend on is not worth the risk right now, so the two are DUPLICATED
# and must be kept in sync. Collapsing that is a follow-up.
set_property PACKAGE_PIN U1 [get_ports {e_gtxc}]
set_property IOSTANDARD LVCMOS33 [get_ports {e_gtxc}]
set_property PACKAGE_PIN T2 [get_ports {e_txen}]
set_property IOSTANDARD LVCMOS33 [get_ports {e_txen}]
set_property PACKAGE_PIN J1 [get_ports {e_txer}]
set_property IOSTANDARD LVCMOS33 [get_ports {e_txer}]
set_property PACKAGE_PIN R2 [get_ports {e_txd[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {e_txd[0]}]
set_property PACKAGE_PIN P1 [get_ports {e_txd[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {e_txd[1]}]
set_property PACKAGE_PIN N2 [get_ports {e_txd[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {e_txd[2]}]
set_property PACKAGE_PIN N1 [get_ports {e_txd[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {e_txd[3]}]
set_property PACKAGE_PIN M1 [get_ports {e_txd[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {e_txd[4]}]
set_property PACKAGE_PIN L2 [get_ports {e_txd[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {e_txd[5]}]
set_property PACKAGE_PIN K2 [get_ports {e_txd[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {e_txd[6]}]
set_property PACKAGE_PIN K1 [get_ports {e_txd[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {e_txd[7]}]
set_property PACKAGE_PIN P4 [get_ports {e_rxc}]
set_property IOSTANDARD LVCMOS33 [get_ports {e_rxc}]
set_property PACKAGE_PIN L3 [get_ports {e_rxdv}]
set_property IOSTANDARD LVCMOS33 [get_ports {e_rxdv}]
set_property PACKAGE_PIN U5 [get_ports {e_rxer}]
set_property IOSTANDARD LVCMOS33 [get_ports {e_rxer}]
set_property PACKAGE_PIN M4 [get_ports {e_rxd[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {e_rxd[0]}]
set_property PACKAGE_PIN N3 [get_ports {e_rxd[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {e_rxd[1]}]
set_property PACKAGE_PIN N4 [get_ports {e_rxd[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {e_rxd[2]}]
set_property PACKAGE_PIN P3 [get_ports {e_rxd[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {e_rxd[3]}]
set_property PACKAGE_PIN R3 [get_ports {e_rxd[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {e_rxd[4]}]
set_property PACKAGE_PIN T3 [get_ports {e_rxd[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {e_rxd[5]}]
set_property PACKAGE_PIN T4 [get_ports {e_rxd[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {e_rxd[6]}]
set_property PACKAGE_PIN T5 [get_ports {e_rxd[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {e_rxd[7]}]
set_property PACKAGE_PIN H1 [get_ports {e_mdio[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {e_mdio[0]}]
set_property PACKAGE_PIN H2 [get_ports {e_mdc}]
set_property IOSTANDARD LVCMOS33 [get_ports {e_mdc}]
set_property PACKAGE_PIN R1 [get_ports {e_resetn}]
set_property IOSTANDARD LVCMOS33 [get_ports {e_resetn}]
set_property PACKAGE_PIN L4 [get_ports {sd_clk}]
set_property IOSTANDARD LVCMOS33 [get_ports {sd_clk}]
set_property PACKAGE_PIN J8 [get_ports {sd_cmd[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sd_cmd[0]}]
set_property PACKAGE_PIN M5 [get_ports {sd_dat_0[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sd_dat_0[0]}]
set_property PACKAGE_PIN M7 [get_ports {sd_dat_1[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sd_dat_1[0]}]
set_property PACKAGE_PIN H6 [get_ports {sd_dat_2[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sd_dat_2[0]}]
set_property PACKAGE_PIN J6 [get_ports {sd_dat_3[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sd_dat_3[0]}]
set_property PACKAGE_PIN N6 [get_ports {sd_cd}]
set_property IOSTANDARD LVCMOS33 [get_ports {sd_cd}]
