/* AUTOGENERATED by com.jopdesign.tools.GenJopConfig */
package com.jopdesign.sys;
public class Config {
public static final boolean USE_SCOPES=false;
public static final boolean USE_SCOPECHECKS=false;
public static final boolean ADD_REF_INFO=false;
public static final boolean MEASURE=true;
}
