/*
  This file is part of JOP, the Java Optimized Processor
    see <http://www.jopdesign.com/>

  Copyright (C) 2001-2008, Martin Schoeberl (martin@jopdesign.com)

  This program is free software: you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation, either version 3 of the License, or
  (at your option) any later version.

  This program is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Public License for more details.

  You should have received a copy of the GNU General Public License
  along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/

// Generated by jop.generate.ConstGenerator from JopConfig
// Assembly: qmtech-ep4cgx150-db-v4
// Do not edit manually — regenerate with:
//   sbt "runMain jop.generate.ConstGeneratorMain <preset> --write"

package com.jopdesign.sys;

/**
 * Constants for the class structure, hardware configuration,
 * and IO addresses.
 *
 * @author martin
 */
public class Const {

	// ====================================================================
	// Class structure constants (architectural, never change)
	// ====================================================================

	/** Size of class header part (difference between class struct and method table) */
	static final int CLASS_HEADR = 5;
	/** Size of instance relative to class struct */
	public static final int CLASS_SIZE = 0;
	/** Pointer to super class relative to class struct */
	public static final int CLASS_SUPER = 3;
	/** Interface table pointer relative to class struct */
	static final int CLASS_IFTAB = 4;
	/** Class info start relative to start of MTAB */
	public static final int MTAB2CLINFO = -5;
	/** GC_INFO field relative to start of MTAB */
	static final int MTAB2GC_INFO = -3;

	// ====================================================================
	// Stack configuration
	// ====================================================================

	/** Size of the on-chip stack cache including microcode scratch area */
	public static final int STACK_SIZE = 65536;
	/** Offset of the real stack in the on-chip RAM (set in jvm.asm) */
	public static final int STACK_OFF = 64;
	/** Constant pool pointer offset in on-chip stack cache */
	public static final int RAM_CP = 1;
	/** Start address of scratchpad RAM */
	public static final int SCRATCHPAD_ADDRESS = 0x400000;

	// ====================================================================
	// Feature flags (derived from JopCoreConfig)
	// ====================================================================

	/**
	 * True if software float support is needed (any core uses Java for float ops).
	 * When false, SoftFloat32 code is dead and eliminated by javac.
	 */
	public static final boolean SUPPORT_FLOAT = true;
	/**
	 * True if software double support is needed.
	 * Always true — no hardware double support yet.
	 */
	public static final boolean SUPPORT_DOUBLE = true;
	/** RTTM is not implemented in SpinalHDL JOP */
	public static final boolean USE_RTTM = false;

	// ====================================================================
	// Exception numbers (architectural)
	// ====================================================================

	/** Hardware exception: stack overflow */
	public static final int EXC_SPOV = 1;
	/** Hardware exception: null pointer */
	public static final int EXC_NP = 2;
	/** Hardware exception: array bounds */
	public static final int EXC_AB = 3;
	/** Hardware exception: RTTM rollback (unused) */
	public static final int EXC_ROLLBACK = 4;
	/** Hardware exception: illegal monitor state */
	public static final int EXC_MON = 5;
	/** Software exception: divide by zero */
	public static final int EXC_DIVZ = 8;

	// ====================================================================
	// I/O base address
	// ====================================================================

	/**
	 * Base address for all I/O devices. Negative value for fast bipush load.
	 * Decoded from address bits — 8 device slots, up to 16 registers each.
	 */
	public static final int IO_BASE = -128; // 0xFFFFFF80

	// ====================================================================
	// System registers (BmbSys, always present)
	// Derived from JopIoSpace.SYS_BASE = 0x80
	// ====================================================================

	/** System counter (read) / Global interrupt enable (write) */
	public static final int IO_CNT = IO_BASE + 0;
	/** Global interrupt enable (alias for IO_CNT write) */
	public static final int IO_INT_ENA = IO_CNT;
	/** Microsecond counter (read) / Timer interrupt (write) */
	public static final int IO_US_CNT = IO_BASE + 0x01;
	/** Timer interrupt (alias for IO_US_CNT write) */
	public static final int IO_TIMER = IO_US_CNT;
	/** Software interrupt trigger (write) / Interrupt number (read) */
	public static final int IO_SWINT = IO_BASE + 2;
	/** Interrupt number (alias for IO_SWINT read) */
	public static final int IO_INTNR = IO_SWINT;
	/** Watchdog */
	public static final int IO_WD = IO_BASE + 3;
	/** Exception register */
	public static final int IO_EXCPT = IO_BASE + 4;
	/** Lock acquire */
	public static final int IO_LOCK = IO_BASE + 5;
	/** Lock release (write) / CPU ID (read) */
	public static final int IO_UNLOCK = IO_BASE + 6;
	/** CPU ID (alias for IO_UNLOCK read) */
	public static final int IO_CPU_ID = IO_UNLOCK;
	/** Signal register */
	public static final int IO_SIGNAL = IO_BASE + 7;
	/** Interrupt mask for individual interrupts */
	public static final int IO_INTMASK = IO_BASE + 8;
	/** Clear all pending interrupts */
	public static final int IO_INTCLEARALL = IO_BASE + 9;
	/** Deadline/RAM counter */
	public static final int IO_DEADLINE = IO_BASE + 10;
	/** CPU count */
	public static final int IO_CPUCNT = IO_BASE + 11;
	/** Performance counter */
	public static final int IO_PERFCNT = IO_BASE + 12;
	/** GC halt register */
	public static final int IO_GC_HALT = IO_BASE + 13;
	/** Usable memory end in words (excludes per-core stack regions) */
	public static final int IO_MEM_SIZE = IO_BASE + 14;
	/** FPU capability register (bit 0: HW single-precision FPU present) */
	public static final int IO_FPU_CAP = IO_BASE + 15;

	// ====================================================================
	// UART registers (BmbUart, always present)
	// Derived from JopIoSpace.UART_BASE = 0x90
	// ====================================================================

	/** UART status register */
	public static final int IO_STATUS = IO_BASE + 0x10;
	/** UART data register */
	public static final int IO_UART = IO_BASE + 0x11;
	/** UART status (alias) */
	public static final int IO_UART_STATUS = IO_STATUS;
	/** UART data (alias) */
	public static final int IO_UART_DATA = IO_UART;
	/** UART TX data register empty mask */
	public static final int MSK_UA_TDRE = 1;
	/** UART RX data register full mask */
	public static final int MSK_UA_RDRF = 2;

	// ====================================================================
	// Peripheral I/O addresses (derived from JopIoSpace)
	// All addresses always defined; use HAS_* flags for runtime checks.
	// ====================================================================

	/** System device base (alias for IO_BASE) */
	public static final int IO_SYS_DEVICE = IO_BASE + 0;
	/** USB port (alias for IO_BASE + 0x20, legacy) */
	public static final int IO_USB = IO_BASE + 0x20;
	public static final int IO_USB_STATUS = IO_USB;
	public static final int IO_USB_DATA = IO_USB + 1;

	/** Ethernet MAC base address */
	public static final int IO_ETH = IO_BASE + 0x18;
	/** MDIO PHY management base address */
	public static final int IO_MDIO = IO_BASE + 0x20;

	/** SD SPI base address */
	public static final int IO_SD_SPI = IO_BASE + 0x28;
	/** VGA DMA framebuffer controller base address */
	public static final int IO_VGA_DMA = IO_BASE + 0x2c;
	/** SD Native base address */
	public static final int IO_SD = IO_BASE + 0x30;
	/** VGA text controller base address */
	public static final int IO_VGA = IO_BASE + 0x40;
	/** Config flash base address */
	public static final int IO_CFG_FLASH = IO_BASE + 0x50;

	/** Hardware divider base address */
	public static final int IO_DIV = IO_BASE + 0x60;
	public static final int IO_REM = IO_DIV + 1;
	public static final int IO_DIV_STS = IO_DIV + 2;

	/** FPU base address */
	public static final int IO_FPU = IO_BASE + 0x70;
	public static final int FPU_A = IO_FPU + 0;
	public static final int FPU_B = IO_FPU + 1;
	public static final int FPU_OP = IO_FPU + 2;
	public static final int FPU_RES = IO_FPU + 3;
	public static final int FPU_OP_ADD = 0;
	public static final int FPU_OP_SUB = 1;
	public static final int FPU_OP_MUL = 2;
	public static final int FPU_OP_DIV = 3;

	// Legacy aliases (referenced by toolchain and older apps)
	public static final int IO_STATUS2 = IO_BASE + 0x30;
	public static final int IO_UART2 = IO_BASE + 0x31;

	// ====================================================================
	// RTTM constants (unused, retained for toolchain compatibility)
	// ====================================================================

	public static final boolean USE_RTTM_BIGMEM = true;
	public static final int MEM_TM_MAGIC = USE_RTTM_BIGMEM ? 0x0C0000 : 0x060000;
	public static final int TM_END_TRANSACTION = 0;
	public static final int TM_START_TRANSACTION = 1;
	public static final int TM_ABORTED = 2;
	public static final int TM_EARLY_COMMIT = 3;

	// ====================================================================
	// Hardware availability (derived from IoConfig)
	// ====================================================================

	/** Board has Ethernet PHY */
	public static final boolean HAS_ETHERNET = false;
	/** Board has SD card interface (SPI or Native) */
	public static final boolean HAS_SD_CARD = false;
	/** Board has VGA output (DMA or Text) */
	public static final boolean HAS_VGA = false;
	/** Board has config flash (EPCS/EPCQ) */
	public static final boolean HAS_CONFIG_FLASH = false;

	// ====================================================================
	// Interrupt configuration
	// ====================================================================

	/**
	 * Number of available interrupts: 1 timer + I/O device interrupts.
	 */
	public static final int NUM_INTERRUPTS = 3;
}
