package jop.generate

import jop.config._
import jop.memory.JopIoSpace
import jop.io.{DeviceTypes, IoAddressAllocator}

/**
 * Generates Const.java from JopConfig.
 *
 * Replaces the manually-maintained Const.java with a config-derived version.
 * I/O addresses for Sys and Uart are fixed (from JopIoSpace).
 * All other device addresses are computed by IoAddressAllocator.
 *
 * Usage:
 *   sbt "runMain jop.generate.ConstGeneratorMain ep4cgx150Serial"
 *   sbt "runMain jop.generate.ConstGeneratorMain wukongSdram --write"
 */
object ConstGenerator {

  /** Convert 8-bit I/O address to Java I/O offset from IO_BASE */
  private def ioOffset(addr8: Int): Int = addr8 - 0x80

  /** Format an I/O offset as hex string for readability */
  private def hexOffset(offset: Int): String =
    if (offset == 0) "0" else f"0x$offset%02x"

  /** Generate complete Const.java source */
  def generate(config: JopConfig): String = {
    // Union of all cores' configs across all systems
    val allCores = config.systems.flatMap(_.coreConfigs)

    // Union of all systems' device presence (works on either devices or ioConfig path)
    val hasEth = config.systems.exists(_.hasEth)
    val hasSdSpi = config.systems.exists(_.hasSdSpi)
    val hasSdNative = config.systems.exists(_.hasSdNative)
    val hasVgaDma = config.systems.exists(_.hasDevice("vgadma"))
    val hasVgaText = config.systems.exists(_.hasDevice("vgatext"))
    val hasCfgFlash = config.systems.exists(_.hasConfigFlash)

    // Build superset devices from all systems for address allocation
    val supersetDevices: Map[String, DeviceInstance] = config.systems.flatMap(_.effectiveDevices).toMap
    val bootName = DeviceTypes.bootDeviceName(supersetDevices)
    val allocatedDevices = IoAddressAllocator.allocate(
      DeviceTypes.toDescriptorsForAllocation(supersetDevices, bootName))
    val addrMap: Map[String, Int] = allocatedDevices.map(ad => ad.descriptor.name -> ad.baseAddr).toMap

    // Helper: get allocated base address for a device, or 0x80 (IO_BASE) as fallback
    def devAddr(name: String): String = addrMap.get(name) match {
      case Some(addr) => hexOffset(ioOffset(addr))
      case None => "0"
    }

    // Feature flags: true if ANY core uses Java (software) for that category
    val supportFloat = allCores.exists { c =>
      import Implementation.Java
      Seq(c.fadd, c.fsub, c.fmul, c.fdiv, c.fneg, c.i2f, c.f2i, c.fcmpl, c.fcmpg)
        .contains(Java)
    }

    // Number of interrupts: timer + max numIoInt across systems
    val maxNumIoInt = config.systems.map(sys => DeviceTypes.interruptCount(sys.effectiveDevices)).max
    val numInterrupts = 1 + maxNumIoInt

    val sb = new StringBuilder
    sb.append(
      s"""/*
         |  This file is part of JOP, the Java Optimized Processor
         |    see <http://www.jopdesign.com/>
         |
         |  Copyright (C) 2001-2008, Martin Schoeberl (martin@jopdesign.com)
         |
         |  This program is free software: you can redistribute it and/or modify
         |  it under the terms of the GNU General Public License as published by
         |  the Free Software Foundation, either version 3 of the License, or
         |  (at your option) any later version.
         |
         |  This program is distributed in the hope that it will be useful,
         |  but WITHOUT ANY WARRANTY; without even the implied warranty of
         |  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
         |  GNU General Public License for more details.
         |
         |  You should have received a copy of the GNU General Public License
         |  along with this program.  If not, see <http://www.gnu.org/licenses/>.
         |*/
         |
         |// Generated by jop.generate.ConstGenerator from JopConfig
         |// Assembly: ${config.assembly.name}
         |// Do not edit manually — regenerate with:
         |//   sbt "runMain jop.generate.ConstGeneratorMain <preset> --write"
         |
         |package com.jopdesign.sys;
         |
         |/**
         | * Constants for the class structure, hardware configuration,
         | * and IO addresses.
         | *
         | * @author martin
         | */
         |public class Const {
         |
         |	// ====================================================================
         |	// Class structure constants (architectural, never change)
         |	// ====================================================================
         |
         |	/** Size of class header part (difference between class struct and method table) */
         |	static final int CLASS_HEADR = 5;
         |	/** Size of instance relative to class struct */
         |	public static final int CLASS_SIZE = 0;
         |	/** Pointer to super class relative to class struct */
         |	public static final int CLASS_SUPER = 3;
         |	/** Interface table pointer relative to class struct */
         |	static final int CLASS_IFTAB = 4;
         |	/** Class info start relative to start of MTAB */
         |	public static final int MTAB2CLINFO = -5;
         |	/** GC_INFO field relative to start of MTAB */
         |	static final int MTAB2GC_INFO = -3;
         |
         |	// ====================================================================
         |	// Stack configuration
         |	// ====================================================================
         |
         |	/** Size of the on-chip stack cache including microcode scratch area */
         |	public static final int STACK_SIZE = 65536;
         |	/** Offset of the real stack in the on-chip RAM (set in jvm.asm) */
         |	public static final int STACK_OFF = 64;
         |	/** Constant pool pointer offset in on-chip stack cache */
         |	public static final int RAM_CP = 1;
         |	/** Start address of scratchpad RAM */
         |	public static final int SCRATCHPAD_ADDRESS = 0x400000;
         |
         |	// ====================================================================
         |	// Feature flags (derived from JopCoreConfig)
         |	// ====================================================================
         |
         |	/**
         |	 * True if software float support is needed (any core uses Java for float ops).
         |	 * When false, SoftFloat32 code is dead and eliminated by javac.
         |	 */
         |	public static final boolean SUPPORT_FLOAT = $supportFloat;
         |	/**
         |	 * True if software double support is needed.
         |	 * Always true — no hardware double support yet.
         |	 */
         |	public static final boolean SUPPORT_DOUBLE = true;
         |	/** RTTM is not implemented in SpinalHDL JOP */
         |	public static final boolean USE_RTTM = false;
         |
         |	// ====================================================================
         |	// Exception numbers (architectural)
         |	// ====================================================================
         |
         |	/** Hardware exception: stack overflow */
         |	public static final int EXC_SPOV = 1;
         |	/** Hardware exception: null pointer */
         |	public static final int EXC_NP = 2;
         |	/** Hardware exception: array bounds */
         |	public static final int EXC_AB = 3;
         |	/** Hardware exception: RTTM rollback (unused) */
         |	public static final int EXC_ROLLBACK = 4;
         |	/** Hardware exception: illegal monitor state */
         |	public static final int EXC_MON = 5;
         |	/** Software exception: divide by zero */
         |	public static final int EXC_DIVZ = 8;
         |
         |	// ====================================================================
         |	// I/O base address
         |	// ====================================================================
         |
         |	/**
         |	 * Base address for all I/O devices. Negative value for fast bipush load.
         |	 * Decoded from address bits — 8 device slots, up to 16 registers each.
         |	 */
         |	public static final int IO_BASE = -128; // 0xFFFFFF80
         |
         |	// ====================================================================
         |	// System registers (Sys, always present, fixed at 0xF0)
         |	// ====================================================================
         |
         |	/** System counter (read) / Global interrupt enable (write) */
         |	public static final int IO_CNT = IO_BASE + ${hexOffset(ioOffset(JopIoSpace.SYS_CNT))};
         |	/** Global interrupt enable (alias for IO_CNT write) */
         |	public static final int IO_INT_ENA = IO_CNT;
         |	/** Microsecond counter (read) / Timer interrupt (write) */
         |	public static final int IO_US_CNT = IO_BASE + ${hexOffset(ioOffset(JopIoSpace.SYS_US_CNT))};
         |	/** Timer interrupt (alias for IO_US_CNT write) */
         |	public static final int IO_TIMER = IO_US_CNT;
         |	/** Software interrupt trigger (write) / Interrupt number (read) */
         |	public static final int IO_SWINT = IO_BASE + ${ioOffset(JopIoSpace.SYS_BASE + 2)};
         |	/** Interrupt number (alias for IO_SWINT read) */
         |	public static final int IO_INTNR = IO_SWINT;
         |	/** Watchdog */
         |	public static final int IO_WD = IO_BASE + ${ioOffset(JopIoSpace.SYS_WD)};
         |	/** Exception register */
         |	public static final int IO_EXCPT = IO_BASE + ${ioOffset(JopIoSpace.SYS_EXC)};
         |	/** Lock acquire */
         |	public static final int IO_LOCK = IO_BASE + ${ioOffset(JopIoSpace.SYS_LOCK)};
         |	/** Lock release (write) / CPU ID (read) */
         |	public static final int IO_UNLOCK = IO_BASE + ${ioOffset(JopIoSpace.SYS_CPU_ID)};
         |	/** CPU ID (alias for IO_UNLOCK read) */
         |	public static final int IO_CPU_ID = IO_UNLOCK;
         |	/** Signal register */
         |	public static final int IO_SIGNAL = IO_BASE + ${ioOffset(JopIoSpace.SYS_SIGNAL)};
         |	/** Interrupt mask for individual interrupts */
         |	public static final int IO_INTMASK = IO_BASE + ${ioOffset(JopIoSpace.SYS_BASE + 8)};
         |	/** Clear all pending interrupts */
         |	public static final int IO_INTCLEARALL = IO_BASE + ${ioOffset(JopIoSpace.SYS_BASE + 9)};
         |	/** Deadline/RAM counter */
         |	public static final int IO_DEADLINE = IO_BASE + ${ioOffset(JopIoSpace.SYS_BASE + 10)};
         |	/** CPU count */
         |	public static final int IO_CPUCNT = IO_BASE + ${ioOffset(JopIoSpace.SYS_BASE + 11)};
         |	/** Performance counter */
         |	public static final int IO_PERFCNT = IO_BASE + ${ioOffset(JopIoSpace.SYS_BASE + 12)};
         |	/** GC halt register */
         |	public static final int IO_GC_HALT = IO_BASE + ${ioOffset(JopIoSpace.SYS_BASE + 13)};
         |	/** Usable memory end in words (excludes per-core stack regions) */
         |	public static final int IO_MEM_SIZE = IO_BASE + ${ioOffset(JopIoSpace.SYS_BASE + 14)};
         |	/** FPU capability register (bit 0: HW single-precision FPU present) */
         |	public static final int IO_FPU_CAP = IO_BASE + ${ioOffset(JopIoSpace.SYS_BASE + 15)};
         |
         |	// ====================================================================
         |	// Boot device registers (UART or cfgFlash, fixed at 0xEE)
         |	// ====================================================================
         |
         |	/** UART status register */
         |	public static final int IO_STATUS = IO_BASE + ${hexOffset(ioOffset(JopIoSpace.UART_STATUS))};
         |	/** UART data register */
         |	public static final int IO_UART = IO_BASE + ${hexOffset(ioOffset(JopIoSpace.UART_DATA))};
         |	/** UART status (alias) */
         |	public static final int IO_UART_STATUS = IO_STATUS;
         |	/** UART data (alias) */
         |	public static final int IO_UART_DATA = IO_UART;
         |	/** UART TX data register empty mask */
         |	public static final int MSK_UA_TDRE = 1;
         |	/** UART RX data register full mask */
         |	public static final int MSK_UA_RDRF = 2;
         |""".stripMargin)

    // Peripheral I/O addresses (from IoAddressAllocator)
    sb.append(
      s"""
         |	// ====================================================================
         |	// Peripheral I/O addresses (dynamically allocated by IoAddressAllocator)
         |	// All addresses always defined; use HAS_* flags for runtime checks.
         |	// ====================================================================
         |
         |	/** System device base (alias for IO_BASE + SYS offset) */
         |	public static final int IO_SYS_DEVICE = IO_BASE + ${hexOffset(ioOffset(JopIoSpace.SYS_BASE))};
         |	/** Ethernet controller base address (MAC at +0, MDIO at +8) */
         |	public static final int IO_ETH = IO_BASE + ${devAddr("eth")};
         |	/** MDIO PHY management base address (ETH base + 8) */
         |	public static final int IO_MDIO = IO_ETH + 8;
         |	/** USB port (legacy alias — shares MDIO address slot) */
         |	public static final int IO_USB = IO_MDIO;
         |	public static final int IO_USB_STATUS = IO_USB;
         |	public static final int IO_USB_DATA = IO_USB + 1;
         |
         |	/** SD SPI base address */
         |	public static final int IO_SD_SPI = IO_BASE + ${devAddr("sdSpi")};
         |	/** VGA DMA framebuffer controller base address */
         |	public static final int IO_VGA_DMA = IO_BASE + ${devAddr("vgaDma")};
         |	/** SD Native base address */
         |	public static final int IO_SD = IO_BASE + ${devAddr("sdNative")};
         |	/** VGA text controller base address */
         |	public static final int IO_VGA = IO_BASE + ${devAddr("vgaText")};
         |	/** Config flash base address */
         |	public static final int IO_CFG_FLASH = IO_BASE + ${devAddr("cfgFlash")};
         |
         |	// Legacy aliases (referenced by toolchain and older apps)
         |	public static final int IO_STATUS2 = IO_BASE + 0x30;
         |	public static final int IO_UART2 = IO_BASE + 0x31;
         |""".stripMargin)

    // RTTM constants (referenced by ReplaceAtomicAnnotation in toolchain)
    sb.append(
      s"""
         |	// ====================================================================
         |	// RTTM constants (unused, retained for toolchain compatibility)
         |	// ====================================================================
         |
         |	public static final boolean USE_RTTM_BIGMEM = true;
         |	public static final int MEM_TM_MAGIC = USE_RTTM_BIGMEM ? 0x0C0000 : 0x060000;
         |	public static final int TM_END_TRANSACTION = 0;
         |	public static final int TM_START_TRANSACTION = 1;
         |	public static final int TM_ABORTED = 2;
         |	public static final int TM_EARLY_COMMIT = 3;
         |""".stripMargin)

    // Hardware availability and interrupts
    sb.append(
      s"""
         |	// ====================================================================
         |	// Hardware availability (derived from device config)
         |	// ====================================================================
         |
         |	/** Board has Ethernet PHY */
         |	public static final boolean HAS_ETHERNET = $hasEth;
         |	/** Board has SD card interface (SPI or Native) */
         |	public static final boolean HAS_SD_CARD = ${hasSdSpi || hasSdNative};
         |	/** Board has VGA output (DMA or Text) */
         |	public static final boolean HAS_VGA = ${hasVgaDma || hasVgaText};
         |	/** Board has config flash (EPCS/EPCQ) */
         |	public static final boolean HAS_CONFIG_FLASH = $hasCfgFlash;
         |
         |	// ====================================================================
         |	// Interrupt configuration
         |	// ====================================================================
         |
         |	/**
         |	 * Number of available interrupts: 1 timer + I/O device interrupts.
         |	 */
         |	public static final int NUM_INTERRUPTS = $numInterrupts;
         |}
         |""".stripMargin)

    sb.toString
  }
}

/** Generate Const.java from a JopConfig preset */
object ConstGeneratorMain extends App {
  import jop.system.JopTopVerilog

  val preset = args.headOption.getOrElse("ep4cgx150Serial")
  val writeToFile = args.contains("--write")
  val config = JopTopVerilog.resolvePreset(preset, args.filterNot(_ == "--write"))

  val source = ConstGenerator.generate(config)

  if (writeToFile) {
    val path = "java/runtime/src/jop/com/jopdesign/sys/Const.java"
    val writer = new java.io.PrintWriter(path)
    writer.print(source)
    writer.close()
    println(s"Wrote $path")
  } else {
    println(source)
  }
}
