package jop.generate

import jop.config._
import jop.memory.JopIoSpace
import jop.io.{DeviceTypes, IoAddressAllocator}

/**
 * Generates Const.java from JopConfig.
 *
 * Replaces the manually-maintained Const.java with a config-derived version.
 * I/O addresses for Sys and Uart are fixed (from JopIoSpace).
 * All other device addresses are computed by IoAddressAllocator.
 *
 * Usage:
 *   sbt "runMain jop.generate.ConstGeneratorMain ep4cgx150Serial"
 *   sbt "runMain jop.generate.ConstGeneratorMain wukongSdram --write"
 */
object ConstGenerator {

  /** The method-size limit this build can execute, in WORDS.
    *
    * Pulled out of `generate` so the linker can be told the number instead of
    * compiling against it. `Const.METHOD_MAX_SIZE` is a `static final int`, so
    * javac INLINES it into JopMethodInfo.class -- which is the only reason
    * jopizer.jar was ever a per-configuration artefact. See status item 140.
    */
  def methodMaxWords(config: JopConfig): Int = {
    val allCores = config.resolvedSystems.map(_.coreConfig)
    val minJpc = allCores.map(_.jpcWidth).min
    val hw = math.min(1 << (minJpc - 2), 1023)
    val overrides = allCores.flatMap(_.methodMaxSizeOverride).map(_ / 4)
    require(overrides.forall(_ <= hw),
      s"methodMaxSizeOverride asks for ${overrides.max * 4} bytes but this build can " +
      s"execute at most ${hw * 4} (jpcWidth $minJpc). It may only lower the limit.")
    (hw +: overrides).min
  }

  /** Everything JOPizer needs from the configuration, as DATA.
    *
    * Four values, and they are the whole of the linker's config-dependence:
    * three limits read by JopMethodInfo and the RTTM magic used by
    * ReplaceAtomicAnnotation. Emitting them lets the linker be built once and
    * told which machine it is linking for, rather than compiled per machine.
    *
    * METHOD_MAX_LOCALS/ARGS are 5-bit fields in the method struct's word2, so
    * they are a FORMAT limit rather than a configurable one -- they are written
    * here anyway, so the linker has ONE source for its limits instead of two.
    */
  def linkerProperties(config: JopConfig): String = {
    val useRttmBigmem = true
    val memTmMagic = if (useRttmBigmem) 0x0C0000 else 0x060000
    s"""# GENERATED by jop.generate.ConstGenerator -- do not edit.
       |#
       |# What the linker needs to know about the target, passed at RUNTIME via
       |# -Djop.linker.config=<this file>. The values used to reach JOPizer by
       |# being compiled into it from Const.java, which made jopizer.jar a
       |# per-configuration artefact and let a jar built for one preset link
       |# another preset's image (status item 140).
       |method.max.size=${methodMaxWords(config) * 4}
       |method.max.locals=31
       |method.max.args=31
       |mem.tm.magic=$memTmMagic
       |""".stripMargin
  }

  /** Convert 8-bit I/O address to Java I/O offset from IO_BASE */
  private def ioOffset(addr8: Int): Int = addr8 - 0x80

  /** Format an I/O offset as hex string for readability */
  private def hexOffset(offset: Int): String =
    if (offset == 0) "0" else f"0x$offset%02x"

  /** Generate complete Const.java source */
  def generate(config: JopConfig): String = {
    // Union of all cores' configs across all systems
    val allCores = config.systems.flatMap(_.coreConfigs)

    // THE LINKER'S METHOD-SIZE LIMIT, DERIVED FROM THE HARDWARE — status item 137.
    //
    // Two independent ceilings, and the smaller wins:
    //
    //   cache capacity  a method is loaded WHOLE into the method cache, which
    //                   holds 2^(jpcWidth-2) words.
    //   struct format   `word1 = codeAddress << 10 | len`, so `len` is 10 bits
    //                   and cannot express more than 1023 words whatever the
    //                   cache size.
    //
    // JOPizer hardcoded 2048 bytes. That was correct for a 2 KB cache
    // (jpcWidth 11 gives exactly 512 words = 2048 bytes) and was never updated
    // when the default became jpcWidth 13 — an 8 KB cache that can hold a
    // 1023-word method. The linker has been refusing methods the hardware could
    // run, and one preset uses jpcWidth 15.
    //
    // The MINIMUM across cores: a heterogeneous SMP image must run on all of
    // them, so the smallest cache sets the limit.
    val minJpcWidth = allCores.map(_.jpcWidth).min
    val hwMethodMaxWords = math.min(1 << (minJpcWidth - 2), 1023)
    // NOTE: methodMaxWords below must agree with ConstGenerator.methodMaxWords,
    // which the linker properties use. Same expression, deliberately not a
    // second copy of the RULE -- see the require() right after it.
    // An explicit cap builds a PORTABLE image -- see methodMaxSizeOverride. It
    // may only LOWER the limit; asking for more than the hardware can execute
    // would produce an image that does not run, so it is refused here rather
    // than at boot.
    val overrideWords = allCores.flatMap(_.methodMaxSizeOverride).map(_ / 4)
    require(overrideWords.forall(_ <= hwMethodMaxWords),
      s"methodMaxSizeOverride asks for ${overrideWords.max * 4} bytes but this build can " +
      s"execute at most ${hwMethodMaxWords * 4} (jpcWidth $minJpcWidth). It may only lower the limit.")
    val methodMaxWords = (hwMethodMaxWords +: overrideWords).min

    // Union of all systems' device presence
    val hasEth = config.systems.exists(_.hasDevice(DeviceType.Ethernet))
    val hasSdSpi = config.systems.exists(_.hasDevice(DeviceType.SdSpi))
    val hasSdNative = config.systems.exists(_.hasDevice(DeviceType.SdNative))
    val hasVgaDma = config.systems.exists(_.hasDevice(DeviceType.VgaDma))
    val hasVgaText = config.systems.exists(_.hasDevice(DeviceType.VgaText))
    val hasCfgFlash = config.systems.exists(_.hasDevice(DeviceType.CfgFlash))

    // Build superset devices from all systems for address allocation
    val supersetDevices: Map[String, DeviceInstance] = config.systems.flatMap(_.effectiveDevices).toMap
    val bootName = DeviceTypes.bootDeviceName(supersetDevices)
    val allocatedDevices = IoAddressAllocator.allocate(
      DeviceTypes.toDescriptorsForAllocation(supersetDevices, bootName))
    val addrMap: Map[String, Int] = allocatedDevices.map(ad => ad.descriptor.name -> ad.baseAddr).toMap

    // Helper: get allocated base address for a device, or 0x80 (IO_BASE) as fallback
    def devAddr(name: String): String = addrMap.get(name) match {
      case Some(addr) => hexOffset(ioOffset(addr))
      case None => "0"
    }

    // Feature flags: true if ANY core uses Java (software) for that category
    val supportFloat = allCores.exists(_.needsJavaFloat)

    // Number of interrupts: timer + max numIoInt across systems
    val maxNumIoInt = config.systems.map(sys => DeviceTypes.interruptCount(sys.effectiveDevices)).max
    val numInterrupts = 1 + maxNumIoInt

    val sb = new StringBuilder
    sb.append(
      s"""/*
         |  This file is part of JOP, the Java Optimized Processor
         |    see <http://www.jopdesign.com/>
         |
         |  Copyright (C) 2001-2008, Martin Schoeberl (martin@jopdesign.com)
         |
         |  This program is free software: you can redistribute it and/or modify
         |  it under the terms of the GNU General Public License as published by
         |  the Free Software Foundation, either version 3 of the License, or
         |  (at your option) any later version.
         |
         |  This program is distributed in the hope that it will be useful,
         |  but WITHOUT ANY WARRANTY; without even the implied warranty of
         |  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
         |  GNU General Public License for more details.
         |
         |  You should have received a copy of the GNU General Public License
         |  along with this program.  If not, see <http://www.gnu.org/licenses/>.
         |*/
         |
         |// Generated by jop.generate.ConstGenerator from JopConfig
         |// Assembly: ${config.assembly.name}
         |// Do not edit manually — regenerate with:
         |//   sbt "runMain jop.generate.ConstGeneratorMain <preset> --write"
         |
         |package com.jopdesign.sys;
         |
         |/**
         | * Constants for the class structure, hardware configuration,
         | * and IO addresses.
         | *
         | * @author martin
         | */
         |public class Const {
         |
         |	// ====================================================================
         |	// Class structure constants (architectural, never change)
         |	// ====================================================================
         |
         |	/** Size of class header part (difference between class struct and method table) */
         |	static final int CLASS_HEADR = 5;
         |	/** Size of instance relative to class struct */
         |	public static final int CLASS_SIZE = 0;
         |	/** Pointer to super class relative to class struct */
         |	public static final int CLASS_SUPER = 3;
         |	/** Interface table pointer relative to class struct */
         |	static final int CLASS_IFTAB = 4;
         |	/** Class info start relative to start of MTAB */
         |	public static final int MTAB2CLINFO = -5;
         |	/** GC_INFO field relative to start of MTAB */
         |	static final int MTAB2GC_INFO = -3;
         |
         |	// ====================================================================
         |	// Stack configuration
         |	// ====================================================================
         |
         |	/** Size of the on-chip stack cache including microcode scratch area */
         |	public static final int STACK_SIZE = 65536;
         |	/** Offset of the real stack in the on-chip RAM (set in jvm.asm) */
         |	public static final int STACK_OFF = 64;
         |	/** Constant pool pointer offset in on-chip stack cache */
         |	public static final int RAM_CP = 1;
         |	/** Start address of scratchpad RAM */
         |	public static final int SCRATCHPAD_ADDRESS = 0x400000;
         |
         |	// ====================================================================
         |	// Method size limit — DERIVED FROM THIS CONFIGURATION, not hardcoded
         |	// ====================================================================
         |
         |	/**
         |	 * Largest method this build can execute, in BYTES.
         |	 *
         |	 * The smaller of the method cache's capacity (2^(jpcWidth-2) words)
         |	 * and what the method struct can express (`len` is 10 bits, so 1023
         |	 * words). JOPizer refuses anything larger, naming the class — a method
         |	 * over this limit cannot be invoked at all.
         |	 *
         |	 * jpcWidth for this build: ${minJpcWidth} (${1 << minJpcWidth} bytes of cache),
         |	 * hardware ceiling ${hwMethodMaxWords * 4} bytes${if (methodMaxWords < hwMethodMaxWords) s", capped to ${methodMaxWords * 4} by methodMaxSizeOverride" else ""}.
         |	 */
         |	public static final int METHOD_MAX_SIZE = ${methodMaxWords * 4};
         |	/** Locals and args are 5-bit fields in the method struct's word2
         |	 *  (`cpoolAddress << 10 | mreallocals << 5 | margs`), so 31 is a FORMAT
         |	 *  limit, not a cache one. Changing it means changing that packing and
         |	 *  every reader of it — microcode included. Named here so a future
         |	 *  change is one edit rather than a search. */
         |	public static final int METHOD_MAX_LOCALS = 31;
         |	public static final int METHOD_MAX_ARGS = 31;
         |
         |	// ====================================================================
         |	// Feature flags (derived from JopCoreConfig)
         |	// ====================================================================
         |
         |	/**
         |	 * True if software float support is needed (any core uses Java for float ops).
         |	 * When false, SoftFloat32 code is dead and eliminated by javac.
         |	 */
         |	public static final boolean SUPPORT_FLOAT = $supportFloat;
         |	/**
         |	 * True if software double support is needed.
         |	 * Always true — no hardware double support yet.
         |	 */
         |	public static final boolean SUPPORT_DOUBLE = true;
         |	/** RTTM is not implemented in SpinalHDL JOP */
         |	public static final boolean USE_RTTM = false;
         |
         |	// ====================================================================
         |	// Exception numbers (architectural)
         |	// ====================================================================
         |
         |	/** Hardware exception: stack overflow */
         |	public static final int EXC_SPOV = 1;
         |	/** Hardware exception: null pointer */
         |	public static final int EXC_NP = 2;
         |	/** Hardware exception: array bounds */
         |	public static final int EXC_AB = 3;
         |	/** Hardware exception: RTTM rollback (unused) */
         |	public static final int EXC_ROLLBACK = 4;
         |	/** Hardware exception: illegal monitor state */
         |	public static final int EXC_MON = 5;
         |	/** Software exception: divide by zero */
         |	public static final int EXC_DIVZ = 8;
         |
         |	// ====================================================================
         |	// I/O base address
         |	// ====================================================================
         |
         |	/**
         |	 * Base address for all I/O devices. Negative value for fast bipush load.
         |	 * Decoded from address bits — 8 device slots, up to 16 registers each.
         |	 */
         |	public static final int IO_BASE = -128; // 0xFFFFFF80
         |
         |	// ====================================================================
         |	// System registers (Sys, always present, fixed at 0xF0)
         |	// ====================================================================
         |
         |	/** System counter (read) / Global interrupt enable (write) */
         |	public static final int IO_CNT = IO_BASE + ${hexOffset(ioOffset(JopIoSpace.SYS_CNT))};
         |	/** Global interrupt enable (alias for IO_CNT write) */
         |	public static final int IO_INT_ENA = IO_CNT;
         |	/** Microsecond counter (read) / Timer interrupt (write) */
         |	public static final int IO_US_CNT = IO_BASE + ${hexOffset(ioOffset(JopIoSpace.SYS_US_CNT))};
         |	/** Timer interrupt (alias for IO_US_CNT write) */
         |	public static final int IO_TIMER = IO_US_CNT;
         |	/** Software interrupt trigger (write) / Interrupt number (read) */
         |	public static final int IO_SWINT = IO_BASE + ${ioOffset(JopIoSpace.SYS_BASE + 2)};
         |	/** Interrupt number (alias for IO_SWINT read) */
         |	public static final int IO_INTNR = IO_SWINT;
         |	/** Watchdog */
         |	public static final int IO_WD = IO_BASE + ${ioOffset(JopIoSpace.SYS_WD)};
         |	/** Exception register */
         |	public static final int IO_EXCPT = IO_BASE + ${ioOffset(JopIoSpace.SYS_EXC)};
         |	/** Lock acquire */
         |	public static final int IO_LOCK = IO_BASE + ${ioOffset(JopIoSpace.SYS_LOCK)};
         |	/** Lock release (write) / CPU ID (read) */
         |	public static final int IO_UNLOCK = IO_BASE + ${ioOffset(JopIoSpace.SYS_CPU_ID)};
         |	/** CPU ID (alias for IO_UNLOCK read) */
         |	public static final int IO_CPU_ID = IO_UNLOCK;
         |	/** Signal register */
         |	public static final int IO_SIGNAL = IO_BASE + ${ioOffset(JopIoSpace.SYS_SIGNAL)};
         |	/** Interrupt mask for individual interrupts */
         |	public static final int IO_INTMASK = IO_BASE + ${ioOffset(JopIoSpace.SYS_BASE + 8)};
         |	/** Clear all pending interrupts */
         |	public static final int IO_INTCLEARALL = IO_BASE + ${ioOffset(JopIoSpace.SYS_BASE + 9)};
         |	/** Deadline/RAM counter */
         |	public static final int IO_DEADLINE = IO_BASE + ${ioOffset(JopIoSpace.SYS_BASE + 10)};
         |	/** CPU count */
         |	public static final int IO_CPUCNT = IO_BASE + ${ioOffset(JopIoSpace.SYS_BASE + 11)};
         |	/** Performance counter */
         |	public static final int IO_PERFCNT = IO_BASE + ${ioOffset(JopIoSpace.SYS_BASE + 12)};
         |	/** GC halt register */
         |	public static final int IO_GC_HALT = IO_BASE + ${ioOffset(JopIoSpace.SYS_BASE + 13)};
         |	/** Usable memory end in words (excludes per-core stack regions) */
         |	public static final int IO_MEM_SIZE = IO_BASE + ${ioOffset(JopIoSpace.SYS_BASE + 14)};
         |	/** FPU capability register (bit 0: HW single-precision FPU present) */
         |	public static final int IO_FPU_CAP = IO_BASE + ${ioOffset(JopIoSpace.SYS_BASE + 15)};
         |
         |	/**
         |	 * Cross-core GC roots. A collector cannot see another core's stack --
         |	 * Native.rdIntMem reads core-private RAM -- so objects reachable only
         |	 * from another core's stack were collected while live. These reach a
         |	 * HALTED core's roots.
         |	 *
         |	 * The sys device decodes 4 bits and all 16 names are taken, so these
         |	 * use the free DIRECTION of two existing addresses: IO_ROOT_SEL is the
         |	 * write side of IO_MEM_SIZE, IO_ROOT_DATA the read side of IO_GC_HALT.
         |	 * That is why each is strictly write-only or read-only.
         |	 *
         |	 * Write IO_ROOT_SEL to choose, then read IO_ROOT_DATA:
         |	 *   bits  7..0  index (stack RAM word address)
         |	 *   bits 11..8  target core id
         |	 *   bits 13..12 what: 0 = stack word, 1 = SP, 2 = A, 3 = B
         |	 */
         |	public static final int IO_ROOT_SEL  = IO_BASE + ${ioOffset(JopIoSpace.SYS_BASE + 14)};
         |	public static final int IO_ROOT_DATA = IO_BASE + ${ioOffset(JopIoSpace.SYS_BASE + 13)};
         |	public static final int ROOT_WHAT_STACK = 0;
         |	public static final int ROOT_WHAT_SP    = 1 << 12;
         |	public static final int ROOT_WHAT_A     = 2 << 12;
         |	public static final int ROOT_WHAT_B     = 3 << 12;
         |
         |	// ====================================================================
         |	// Zero-fill DMA registers (BmbMemoryController, fixed at 0xEC-0xED)
         |	// ====================================================================
         |	/** Zero-fill DMA: start word address — write to latch */
         |	public static final int IO_ZERO_START = IO_BASE + ${ioOffset(JopIoSpace.ZERO_START)};
         |	/** Zero-fill DMA: end word address, exclusive — write to launch (blocks until done) */
         |	public static final int IO_ZERO_END = IO_BASE + ${ioOffset(JopIoSpace.ZERO_END)};
         |
         |	// ====================================================================
         |	// Card table (generational GC card-marking barrier, JopCore, 0xE0-0xE7)
         |	// ====================================================================
         |	/** Card table: tenure base word address (write) */
         |	public static final int IO_CARD_TENURE_LO = IO_BASE + ${ioOffset(JopIoSpace.CARD_TENURE_LO)};
         |	/** Card table: tenure top word address, exclusive (write) */
         |	public static final int IO_CARD_TENURE_HI = IO_BASE + ${ioOffset(JopIoSpace.CARD_TENURE_HI)};
         |	/** Card table: 32-card word index for the next DATA read (write) */
         |	public static final int IO_CARD_IDX = IO_BASE + ${ioOffset(JopIoSpace.CARD_IDX)};
         |	/** Card table: 32 cards at IO_CARD_IDX (read) */
         |	public static final int IO_CARD_DATA = IO_BASE + ${ioOffset(JopIoSpace.CARD_DATA)};
         |	/** Card table: cardShift = log2(words per card) (read) */
         |	public static final int IO_CARD_SHIFT = IO_BASE + ${ioOffset(JopIoSpace.CARD_SHIFT)};
         |	/** Card table: number of 32-card words in the table (read) */
         |	public static final int IO_CARD_COUNT = IO_BASE + ${ioOffset(JopIoSpace.CARD_COUNT)};
         |	/** Card table: clear one word=index (write), or -1 to clear all */
         |	public static final int IO_CARD_CLEAR = IO_BASE + ${ioOffset(JopIoSpace.CARD_CLEAR)};
         |
         |	// ====================================================================
         |	// Boot device registers (UART or cfgFlash, fixed at 0xEE)
         |	// ====================================================================
         |
         |	/** UART status register */
         |	public static final int IO_STATUS = IO_BASE + ${hexOffset(ioOffset(JopIoSpace.UART_STATUS))};
         |	/** UART data register */
         |	public static final int IO_UART = IO_BASE + ${hexOffset(ioOffset(JopIoSpace.UART_DATA))};
         |	/** UART status (alias) */
         |	public static final int IO_UART_STATUS = IO_STATUS;
         |	/** UART data (alias) */
         |	public static final int IO_UART_DATA = IO_UART;
         |	/** UART TX data register empty mask */
         |	public static final int MSK_UA_TDRE = 1;
         |	/** UART RX data register full mask */
         |	public static final int MSK_UA_RDRF = 2;
         |""".stripMargin)

    // Peripheral I/O addresses (from IoAddressAllocator)
    sb.append(
      s"""
         |	// ====================================================================
         |	// Peripheral I/O addresses (dynamically allocated by IoAddressAllocator)
         |	// All addresses always defined; use HAS_* flags for runtime checks.
         |	// ====================================================================
         |
         |	/** System device base (alias for IO_BASE + SYS offset) */
         |	public static final int IO_SYS_DEVICE = IO_BASE + ${hexOffset(ioOffset(JopIoSpace.SYS_BASE))};
         |	/** Ethernet controller base address (MAC at +0, MDIO at +8) */
         |	public static final int IO_ETH = IO_BASE + ${devAddr("eth")};
         |	/** MDIO PHY management base address (ETH base + 8) */
         |	public static final int IO_MDIO = IO_ETH + 8;
         |	/** USB port (legacy alias — shares MDIO address slot) */
         |	public static final int IO_USB = IO_MDIO;
         |	public static final int IO_USB_STATUS = IO_USB;
         |	public static final int IO_USB_DATA = IO_USB + 1;
         |
         |	/** SD SPI base address */
         |	public static final int IO_SD_SPI = IO_BASE + ${devAddr("sdSpi")};
         |	/** VGA DMA framebuffer controller base address */
         |	public static final int IO_VGA_DMA = IO_BASE + ${devAddr("vgaDma")};
         |	/** SD Native base address */
         |	public static final int IO_SD = IO_BASE + ${devAddr("sdNative")};
         |	/** VGA text controller base address */
         |	public static final int IO_VGA = IO_BASE + ${devAddr("vgaText")};
         |	/** Config flash base address */
         |	public static final int IO_CFG_FLASH = IO_BASE + ${devAddr("cfgFlash")};
         |
         |	// Legacy aliases (referenced by toolchain and older apps)
         |	public static final int IO_STATUS2 = IO_BASE + 0x30;
         |	public static final int IO_UART2 = IO_BASE + 0x31;
         |""".stripMargin)

    // Per-device register constants for all devices with registerNames
    // Skip boot device (uart/cfgFlash) — already defined in boot device section above
    val devicesWithRegs = allocatedDevices
      .filter(ad => ad.descriptor.registerNames.nonEmpty && !bootName.contains(ad.descriptor.name))
      .sortBy(_.baseAddr)

    if (devicesWithRegs.nonEmpty) {
      sb.append(
        s"""
           |	// ====================================================================
           |	// Per-device register addresses (auto-generated from registerNames)
           |	// ====================================================================
           |""".stripMargin)

      for (ad <- devicesWithRegs) {
        val devName = ad.descriptor.name.toUpperCase
        val baseOffset = ioOffset(ad.baseAddr)
        sb.append(s"\n\t/** ${ad.descriptor.name} base address */\n")
        sb.append(s"\tpublic static final int IO_${devName} = IO_BASE + ${hexOffset(baseOffset)};\n")
        for ((subAddr, regName) <- ad.descriptor.registerNames) {
          val constName = s"IO_${devName}_$regName"
          if (subAddr == 0)
            sb.append(s"\tpublic static final int $constName = IO_${devName};\n")
          else
            sb.append(s"\tpublic static final int $constName = IO_${devName} + $subAddr;\n")
        }
      }
    }

    // RTTM constants (referenced by ReplaceAtomicAnnotation in toolchain)
    sb.append(
      s"""
         |	// ====================================================================
         |	// RTTM constants (unused, retained for toolchain compatibility)
         |	// ====================================================================
         |
         |	public static final boolean USE_RTTM_BIGMEM = true;
         |	public static final int MEM_TM_MAGIC = USE_RTTM_BIGMEM ? 0x0C0000 : 0x060000;
         |	public static final int TM_END_TRANSACTION = 0;
         |	public static final int TM_START_TRANSACTION = 1;
         |	public static final int TM_ABORTED = 2;
         |	public static final int TM_EARLY_COMMIT = 3;
         |""".stripMargin)

    // Hardware availability and interrupts
    sb.append(
      s"""
         |	// ====================================================================
         |	// Hardware availability (derived from device config)
         |	// ====================================================================
         |
         |	/** Board has Ethernet PHY */
         |	public static final boolean HAS_ETHERNET = $hasEth;
         |	/** Board has SD card interface (SPI or Native) */
         |	public static final boolean HAS_SD_CARD = ${hasSdSpi || hasSdNative};
         |	/** Board has VGA output (DMA or Text) */
         |	public static final boolean HAS_VGA = ${hasVgaDma || hasVgaText};
         |	/** Board has config flash (EPCS/EPCQ) */
         |	public static final boolean HAS_CONFIG_FLASH = $hasCfgFlash;
         |
         |	// ====================================================================
         |	// Interrupt configuration
         |	// ====================================================================
         |
         |	/**
         |	 * Number of available interrupts: 1 timer + I/O device interrupts.
         |	 */
         |	public static final int NUM_INTERRUPTS = $numInterrupts;
         |}
         |""".stripMargin)

    sb.toString
  }
}

/** Generate Const.java from a JopConfig preset */
object ConstGeneratorMain extends App {
  import jop.system.JopTopVerilog

  val preset = args.headOption.getOrElse(
  sys.error(
    "no preset given. Pass the preset name as the first argument.\n" +
    "There is deliberately no default: this main writes a constraint or\n" +
    "project file, and a default silently produces a WELL-FORMED file for\n" +
    "the wrong board at the path --write names, which then builds."))
  val writeToFile = args.contains("--write")
  // Same opt-in switch the Verilog generator takes: `buildtree` says WHERE to
  // write, not WHAT to build, so it is filtered out of both the preset
  // resolution and the configuration name.
  val useBuildTree = args.exists(_.equalsIgnoreCase("buildtree"))
  val cfgArgs = args.filterNot(a => a == "--write" || a.equalsIgnoreCase("buildtree"))
  val config = JopTopVerilog.resolvePreset(preset, cfgArgs)

  val source = ConstGenerator.generate(config)

  if (writeToFile) {
    // Const.java is PER CONFIGURATION -- ep4cgx150Serial and wukongSmp differ in
    // SUPPORT_FLOAT alone, and more will follow. Under `buildtree` it goes with
    // the rest of the configuration's artefacts; the legacy path writes into a
    // source tree shared by every configuration, where whichever build ran last
    // wins. See docs/current-status.md item 60.
    // THE LEGACY BRANCH IS GONE. This used to fall back to
    // java/runtime/src/jop/com/jopdesign/sys/Const.java -- a source tree shared
    // by every configuration, where whichever build ran last won. `buildtree`
    // is now the only layout, and every caller passes it, so the fallback was
    // unreachable from the build and survived only as a way back in.
    val javaDir = BuildLayout.default.javaDir(preset, cfgArgs.filterNot(_ == preset))
    val path = s"$javaDir/gen/com/jopdesign/sys/Const.java"
    new java.io.File(path).getParentFile.mkdirs()
    val writer = new java.io.PrintWriter(path)
    writer.print(source)
    writer.close()
    println(s"Wrote $path")

    // The same facts as DATA, for the linker to read at runtime.
    val propsPath = s"$javaDir/gen/jop-linker.properties"
    val pw = new java.io.PrintWriter(propsPath)
    pw.print(ConstGenerator.linkerProperties(config))
    pw.close()
    println(s"Wrote $propsPath")
  } else {
    println(source)
  }
}
