package jop.generate

import jop.config._

/**
 * Lattice .lpf constraint generator — the ECP5 / open-source flow.
 *
 * The third rendering of the same board data, after QsfGenerator (Quartus) and
 * XdcGenerator (Vivado). It exists because the Colorlight i5 was the last board
 * whose build read a HAND-WRITTEN constraint file: its RTL, bitstream and .jop
 * images were all generated, but `nextpnr --lpf` still took pins from a file
 * whose own header said "Mirrored in Board.ColorlightI5 ... keep the two in
 * step". A generated flow that reads a hand-maintained file is not testing the
 * generator, and "keep the two in step" is a promise no build checks.
 *
 * AN .LPF IS THREE FILES IN ONE, which is what makes it different from the
 * other two renderings:
 *
 *   LOCATE COMP   pin assignment      (as .qsf / .xdc PACKAGE_PIN)
 *   IOBUF  PORT   I/O attributes      (as .qsf / .xdc IOSTANDARD + DRIVE)
 *   FREQUENCY /   timing              (as .sdc / .xdc create_clock)
 *   BLOCK ...
 *
 * The timing third is NOT written here -- it comes from TimingConstraints,
 * which already renders itself to .lpf, so the one timing model still serves
 * all three toolchains.
 *
 * WHAT IS CONFIG AND WHAT IS RENDERING. Pins, I/O standard and parked ports are
 * board FACTS and live in `Board`. Drive strength and pull mode are decisions
 * about how to drive a given class of signal on this technology, so they are
 * made here -- an input that needs a defined idle level gets a pull-up, a
 * memory bus gets the strong drive, a strapped-off port gets the weak one.
 */
object LpfGenerator {

  /** Drive strength in mA, by signal class. Memory buses and the UART
    * transmitter drive real loads; a parked or indicator output does not. */
  private def driveFor(port: String): Option[Int] =
    if (port.startsWith("sdram_DQM") ||
        port == "sdram_CKE" || port == "sdram_CSn") Some(4)
    else if (port.startsWith("sdram_")) Some(8)
    else if (port.startsWith("led")) Some(4)
    else if (port == "ser_txd") Some(8)
    else None

  /** Pull mode. The UART receive line must not float when nothing is driving
    * it -- a floating RX reads as a stream of framing errors rather than as
    * silence. Everything else is driven, so it is pulled NONE explicitly
    * rather than left to the tool's default. */
  private def pullFor(port: String): Option[String] =
    if (port == "ser_rxd") Some("UP")
    else if (port == "clk_in" || port.startsWith("led")) Some("NONE")
    else None

  private def locate(port: String, pin: String): String =
    s"""LOCATE COMP "$port" SITE "$pin";\n"""

  private def iobuf(port: String, ioStandard: String): String = {
    val attrs = pullFor(port).map(m => s"PULLMODE=$m").toSeq ++
                Seq(s"IO_TYPE=$ioStandard") ++
                driveFor(port).map(d => s"DRIVE=$d").toSeq
    s"""IOBUF  PORT "$port" ${attrs.mkString(" ")};\n"""
  }

  private def pin(port: String, site: String, ioStandard: String): String =
    locate(port, site) + iobuf(port, ioStandard)

  def generate(config: BoardDesign): String = {
    val assembly = config.assembly
        val board = assembly.boards.head
    val io = board.ioStandard
    val sb = new StringBuilder

    sb.append("# Generated by JOP LpfGenerator -- do not hand-edit.\n")
    sb.append(s"# Assembly: ${assembly.name}\n")
    sb.append(s"# System:   ${config.designName}\n")
    board.fpga.foreach(f => sb.append(s"# FPGA:     ${f.name}\n"))
    sb.append("\n")

    // Timing, from the one model the other two toolchains also render.
    sb.append(TimingConstraints.forConfig(config).toLpf)
    sb.append("\n")

    PinResolver.clockFpgaPin(assembly).foreach { p =>
      sb.append("# Clock\n").append(pin("clk_in", p, io)).append("\n")
    }

    config.resetInput.foreach { r =>
      sb.append(s"# Reset (active ${if (r.activeLow) "low" else "high"})\n")
      sb.append(pin(r.port, r.pin, io)).append("\n")
    }

    val driverPins = PinResolver.devicePins(assembly, config.devices)
    val uart = driverPins.filter(_.verilogPort.startsWith("ser_"))
    if (uart.nonEmpty) {
      sb.append("# UART\n")
      uart.sortBy(_.verilogPort).foreach(p => sb.append(pin(p.verilogPort, p.fpgaPin, io)))
      sb.append("\n")
    }

    val leds = PinResolver.ledPins(assembly).take(config.ledCount)
    if (leds.nonEmpty) {
      sb.append("# LEDs\n")
      leds.foreach(p => sb.append(pin(p.verilogPort, p.fpgaPin, io)))
      sb.append("\n")
    }

    // SDR SDRAM, and only when the SYSTEM uses it -- a board can carry the chip
    // without this design driving it. Same guard as XdcGenerator, for the same
    // reason: constraints for ports the design does not have are a warning, not
    // an error, and warnings scroll past.
    val usesSdr = config.usesSdr
    if (usesSdr) {
      val sdramPins = PinResolver.sdramPins(assembly)
      val clk = PinResolver.sdramClockFpgaPin(assembly)
      if (sdramPins.nonEmpty || clk.isDefined) {
        sb.append("# SDR SDRAM\n")
        clk.foreach(p => sb.append(pin("sdram_clk", p, io)))
        sdramPins.sortBy(p => (busName(p.verilogPort), busIndex(p.verilogPort)))
          .foreach(p => sb.append(pin(p.verilogPort, p.fpgaPin, io)))
        sb.append("\n")
      }
    }

    // Parked ports exist only if the design HAS the interface they belong to.
    // The BRAM-stage i5 has no sdram_* ports at all, and emitting them there
    // constrains ports that do not exist -- the same trap the SDRAM guard above
    // exists for. Gated on the interface, not merely on the board declaring
    // them.
    val parked = board.parkedPins.filterNot {
      case (port, _) => port.startsWith("sdram_") && !usesSdr
    }
    if (parked.nonEmpty) {
      sb.append("# Ports the design has but this board does not wire -- see\n")
      sb.append("# Board.parkedPins for why these get a ball at all.\n")
      parked.toSeq.sortBy(kv => (busName(kv._1), busIndex(kv._1)))
        .foreach { case (port, site) => sb.append(pin(port, site, io)) }
      sb.append("\n")
    }

    sb.toString
  }

  private def busName(port: String): String = port.takeWhile(_ != '[')
  private def busIndex(port: String): Int =
    port.dropWhile(_ != '[').drop(1).takeWhile(_ != ']').toIntOption.getOrElse(-1)
}

/** Writes the .lpf for a preset. `--write <path>`, or stdout. */
object LpfGeneratorMain extends App {
  import jop.system.JopTopVerilog
  val preset = args.headOption.getOrElse(
  sys.error(
    "no preset given. Pass the preset name as the first argument.\n" +
    "There is deliberately no default: this main writes a constraint or\n" +
    "project file, and a default silently produces a WELL-FORMED file for\n" +
    "the wrong board at the path --write names, which then builds."))
  val writeIdx = args.indexOf("--write")
  val outPath = if (writeIdx >= 0 && args.length > writeIdx + 1) Some(args(writeIdx + 1)) else None
  val cfgArgs = args.zipWithIndex.filterNot { case (a, i) =>
    a == "--write" || (writeIdx >= 0 && i == writeIdx + 1)
  }.map(_._1)
  val config = JopTopVerilog.resolvePreset(preset, cfgArgs)
  val text = LpfGenerator.generate(config)
  outPath match {
    case Some(p) =>
      new java.io.File(p).getParentFile.mkdirs()
      val w = new java.io.PrintWriter(p); w.print(text); w.close()
      println(s"Wrote $p")
    case None => print(text)
  }
}
