package jop.generate

import jop.config._

/**
 * Quartus .qsf Pin Assignment Generator
 *
 * Generates set_location_assignment and set_global_assignment lines
 * from JopConfig. Uses PinResolver for shared pin resolution.
 */
object QsfGenerator {

  /** Generate all pin assignments for a JopConfig */
  def pinAssignments(config: BoardDesign): Seq[PinAssignment] = {
    val assembly = config.assembly
    
    val clock = PinResolver.clockFpgaPin(assembly)
      .map(PinAssignment(_, "clk_in")).toSeq
    val sdramClk =
      if (config.usesSdr)
        PinResolver.sdramClockFpgaPin(assembly).map(PinAssignment(_, "sdram_clk")).toSeq
      else Seq.empty
    // Both of these must follow the DESIGN, not the assembly -- the same rule
    // the reset comment below states, which had only ever been applied to
    // reset. A board offering seven LEDs and an SDRAM chip does not mean this
    // design has seven LED ports or any sdram_* ports at all.
    val leds = PinResolver.ledPins(assembly).take(config.ledCount)
    val sdram =
      if (config.usesSdr) PinResolver.sdramPins(assembly) else Seq.empty
    val drivers = PinResolver.devicePins(assembly, config.devices)

    // The reset button, from the SAME predicate JopTop uses to decide whether
    // the port exists. Omitting it left the EP4CGX150's SW1 for Quartus to
    // place wherever it liked (item 57); emitting it unconditionally would
    // assign a port that does not exist on the DDR2/DDR3 tops.
    val reset = config.resetInput.map(r => PinAssignment(r.pin, r.port)).toSeq

    clock ++ sdramClk ++ leds ++ sdram ++ drivers ++ reset
  }

  /** Quartus wants `PIN_A5`; board data does not always say so.
    *
    * Altera board entries are written both ways -- `PIN_B14` on the EP4CGX150,
    * bare `A5` on the A-E115FB -- because the Xilinx and Lattice boards in the
    * same table legitimately use bare names and the convention blurred. A bare
    * name is not rejected by Quartus: `set_location_assignment A5` names a
    * different KIND of location, so the pin silently goes unassigned and the
    * fitter places the port wherever it likes. Normalised here, in the only
    * generator that emits .qsf, so the data cannot get it wrong. */
  private def pinName(p: String): String =
    if (p.startsWith("PIN_")) p else s"PIN_$p"

  /** Format pin assignments as Quartus TCL */
  def toQsf(assignments: Seq[PinAssignment]): String =
    assignments.map { a =>
      s"set_location_assignment ${pinName(a.fpgaPin)} -to ${a.verilogPort}"
    }.mkString("\n")

  /** Per-port I/O standards, for boards where one default is wrong.
    *
    * The A-E115FB is the case that needed it: its clock, reset and LEDs sit in
    * banks shared with the 1.8 V DDR2 interface while the CH340 is 3.3 V, so a
    * single board-wide default cannot describe it. Keyed by port name; a bare
    * name covers a bus, so `led` applies to `led[0]`..`led[3]`. */
  def toIoStandards(config: BoardDesign, assignments: Seq[PinAssignment]): String = {
    val stds = config.assembly.boards.flatMap(_.portIoStandards).toMap
    // A DESIGN NAMES ITS OWN RESET PORT; the board only knows that the reset
    // PIN needs a particular I/O standard. Boards spell it "reset", which
    // matched every JopConfig flow and nothing else -- the DDR2 exerciser calls
    // it `rst_n`, got no standard, and inherited the global 3.3-V LVCMOS on a
    // pin sitting in the 1.8 V DDR2 bank:
    //
    //   Error (169029): Pin rst_n is incompatible with I/O bank 5
    //
    // So a reset port falls back to the board's "reset" entry whatever it is
    // called.
    val resetPort = config.resetInput.map(_.port)
    if (stds.isEmpty) "" else assignments.flatMap { a =>
      val base = a.verilogPort.takeWhile(_ != '[')
      val viaReset = if (resetPort.contains(a.verilogPort)) stds.get("reset") else None
      stds.get(a.verilogPort).orElse(stds.get(base)).orElse(viaReset).map { std =>
        s"""set_instance_assignment -name IO_STANDARD "$std" -to ${a.verilogPort}"""
      }
    }.mkString("\n")
  }

  /** Generate global assignments (FAMILY, DEVICE, TOP_LEVEL_ENTITY) */
  def globalAssignments(config: BoardDesign): String = {
    val fpga = config.fpga
    val family = fpga.family.quartusFamilyName
    Seq(
      s"""set_global_assignment -name FAMILY "$family"""",
      s"set_global_assignment -name DEVICE ${fpga.name}",
      s"set_global_assignment -name TOP_LEVEL_ENTITY ${config.entityName}",
      """set_global_assignment -name STRATIX_DEVICE_IO_STANDARD "3.3-V LVCMOS""""
    ).mkString("\n")
  }

  /** Generate complete QSF pin assignment file */
  def generate(config: BoardDesign): String = {
    val assignments = pinAssignments(config)
    val globals = globalAssignments(config)

    val sb = new StringBuilder
    sb.append("# Generated by JOP QsfGenerator\n")
    sb.append("# Assembly: ").append(config.assembly.name).append("\n")
    sb.append("# System: ").append(config.designName).append("\n\n")

    sb.append("# Global assignments\n")
    sb.append(globals).append("\n\n")

    sb.append("# Pin assignments\n")
    sb.append(toQsf(assignments)).append("\n")

    sb.toString
  }
}

/** Print, or write, the generated Quartus assignments for a preset.
  *
  * `--pins-only` emits just the `set_location_assignment` lines, for inclusion
  * from a hand-written .qsf via
  *
  *     set_global_assignment -name SOURCE_TCL_SCRIPT_FILE generated/pins.tcl
  *
  * WHY THE SPLIT, when the Vivado side simply replaced the whole file. An .xdc
  * holds only constraints; a .qsf holds the whole PROJECT -- the source file
  * list, the SDC reference, junction temperatures, core voltage, configuration
  * pin settings and the SignalTap VIRTUAL_PIN assignments. Fifty such lines in
  * `jop_sdram.qsf` alone, none of which the config knows about. Generating the
  * pins and leaving the project settings hand-written splits it exactly along
  * the line of what JopConfig actually describes.
  *
  * `--write <path>` follows XdcGeneratorMain and ConstGeneratorMain.
  */
object QsfGeneratorMain extends App {
  val base = JopConfig.ep4cgx150Serial
  // Daughter board peripherals for pin reservation
  val dbPeripherals = Map(
    "eth" -> DeviceInstance(DeviceType.Ethernet,
      params = Map("gmii" -> true, "phyDataWidth" -> 8),
      devicePart = Some("RTL8211EG")),
    "sdNative" -> DeviceInstance(DeviceType.SdNative,
      devicePart = Some("SD_CARD")))
  val vga = Map(
    "vga" -> DeviceInstance(DeviceType.VgaDma, devicePart = Some("VGA")))
  // Daughter-board peripherals only when the daughter board is in play. They
  // used to be added unconditionally "for pin reservation", which put ~36
  // assignments for Ethernet and SD ports onto presets that do not instantiate
  // them -- harmless as reservation, wrong as a description of the build.
  val extraDevices = if (args.contains("--dbfpga")) dbPeripherals ++ vga else Map.empty[String, DeviceInstance]
  val config = base.copy(systems = Seq(
    base.system.copy(devices = base.system.devices ++ extraDevices)))

  private val pinsOnly = args.contains("--pins-only")
  private val writeIdx = args.indexOf("--write")
  private val outPath =
    if (writeIdx >= 0 && args.length > writeIdx + 1) Some(args(writeIdx + 1)) else None

  private val body =
    if (pinsOnly)
      "# Generated by JOP QsfGenerator (--pins-only). Included from the .qsf via\n" +
      "# set_global_assignment -name SOURCE_TCL_SCRIPT_FILE. Do not hand-edit.\n" +
      s"# Assembly: ${config.assembly.name}  System: ${config.designName}\n\n" +
      QsfGenerator.toQsf(QsfGenerator.pinAssignments(config)) + "\n"
    else QsfGenerator.generate(config)

  outPath match {
    case Some(path) =>
      val f = new java.io.File(path)
      Option(f.getParentFile).foreach(_.mkdirs())
      val w = new java.io.PrintWriter(f)
      try w.print(body) finally w.close()
      println(s"Wrote $path")
    case None => println(body)
  }
}
