package jop.generate

import jop.config._

/**
 * Quartus .qsf Pin Assignment Generator
 *
 * Generates set_location_assignment and set_global_assignment lines
 * from JopConfig. Uses PinResolver for shared pin resolution.
 */
object QsfGenerator {

  /** Generate all pin assignments for a JopConfig */
  def pinAssignments(config: JopConfig): Seq[PinAssignment] = {
    val assembly = config.assembly
    val sys = config.system

    val clock = PinResolver.clockFpgaPin(assembly)
      .map(PinAssignment(_, "clk_in")).toSeq
    val sdramClk = PinResolver.sdramClockFpgaPin(assembly)
      .map(PinAssignment(_, "sdram_clk")).toSeq
    val leds = PinResolver.ledPins(assembly)
    val sdram = PinResolver.sdramPins(assembly)
    val drivers = PinResolver.devicePins(assembly, sys.effectiveDevices)

    clock ++ sdramClk ++ leds ++ sdram ++ drivers
  }

  /** Format pin assignments as Quartus TCL */
  def toQsf(assignments: Seq[PinAssignment]): String =
    assignments.map { a =>
      s"set_location_assignment ${a.fpgaPin} -to ${a.verilogPort}"
    }.mkString("\n")

  /** Generate global assignments (FAMILY, DEVICE, TOP_LEVEL_ENTITY) */
  def globalAssignments(config: JopConfig): String = {
    val fpga = config.fpga
    val family = fpga.family.quartusFamilyName
    Seq(
      s"""set_global_assignment -name FAMILY "$family"""",
      s"set_global_assignment -name DEVICE ${fpga.name}",
      s"set_global_assignment -name TOP_LEVEL_ENTITY ${config.entityName}",
      """set_global_assignment -name STRATIX_DEVICE_IO_STANDARD "3.3-V LVCMOS""""
    ).mkString("\n")
  }

  /** Generate complete QSF pin assignment file */
  def generate(config: JopConfig): String = {
    val assignments = pinAssignments(config)
    val globals = globalAssignments(config)

    val sb = new StringBuilder
    sb.append("# Generated by JOP QsfGenerator\n")
    sb.append("# Assembly: ").append(config.assembly.name).append("\n")
    sb.append("# System: ").append(config.system.name).append("\n\n")

    sb.append("# Global assignments\n")
    sb.append(globals).append("\n\n")

    sb.append("# Pin assignments\n")
    sb.append(toQsf(assignments)).append("\n")

    sb.toString
  }
}

/** Print generated QSF for EP4CGX150 preset */
object QsfGeneratorMain extends App {
  val base = JopConfig.ep4cgx150Serial
  // Daughter board peripherals for pin reservation
  val dbPeripherals = Map(
    "eth" -> DeviceInstance(DeviceType.Ethernet,
      params = Map("gmii" -> true, "phyDataWidth" -> 8),
      devicePart = Some("RTL8211EG")),
    "sdNative" -> DeviceInstance(DeviceType.SdNative,
      devicePart = Some("SD_CARD")))
  val vga = Map(
    "vga" -> DeviceInstance(DeviceType.VgaDma, devicePart = Some("VGA")))
  val extraDevices = if (args.contains("--dbfpga")) dbPeripherals ++ vga else dbPeripherals
  val config = base.copy(systems = Seq(
    base.system.copy(devices = base.system.devices ++ extraDevices)))

  println(QsfGenerator.generate(config))
}
