package jop.generate

import jop.config._

/**
 * Emit a Tcl script that CREATES the Quartus project, rather than a .qsf.
 *
 * WHY NOT WRITE THE .qsf DIRECTLY. Quartus writes parts of that file itself --
 * `LAST_QUARTUS_VERSION`, the `PARTITION_*` block -- and the format is the
 * tool's, not ours. `project_new` plus assignments lets Quartus author the
 * .qsf/.qpf in whatever form its version wants, while every assignment still
 * comes from JopConfig. The .qsf then stops being a tracked source file and
 * becomes a build artefact, which is the point: it cannot drift from the config
 * because it is regenerated from it.
 *
 *   quartus_sh -t setup_proj.tcl
 *   quartus_map <rev> && quartus_fit <rev> && quartus_asm <rev> && quartus_sta <rev>
 *
 * NOTE ON EDITIONS: Intel's scripting guide shows `quartus_syn`, which is Prime
 * PRO. This project builds on Lite/Standard, where the synthesis executable is
 * `quartus_map`. The Tcl project API is the same in all editions.
 *
 * WHAT IS STILL NOT DERIVED. Junction temperatures, core supply voltage and the
 * device I/O standard are PART properties and the configuration-pin settings are
 * BOARD properties; both are keyed by family here rather than modelled on
 * FpgaDevice/Board, because inventing values for parts nobody has built would be
 * worse than a narrow table. Widen it when a board needs different ones.
 */
object QuartusProject {

  /** The project lives at `build/<config>/quartus`, so repo-root-relative paths
    * are written three levels up, and the PLL -- this configuration's own, at
    * `build/<config>/ip` -- is one level up. Relative rather than absolute, so
    * the project is relocatable and no generated file records this machine's
    * directory layout. */
  def generate(config: JopConfig, revision: String,
               preset: String, buildArgs: Seq[String],
               layout: BuildLayout = BuildLayout.default): String = {
    val sb = new StringBuilder
    val fpga = config.fpga
    val sys = config.system
    val memType = config.resolveMemory(sys).map(_.memType)

    def g(name: String, value: String): Unit =
      sb.append(s"set_global_assignment -name $name $value\n")

    sb.append("# Generated by JOP QuartusProject -- do not hand-edit.\n")
    sb.append(s"# Preset assembly: ${config.assembly.name}, system: ${sys.name}\n")
    sb.append("#\n")
    sb.append("# Creates the project from JopConfig. Quartus writes the .qsf and .qpf\n")
    sb.append("# itself, so both are build outputs and neither is tracked.\n\n")
    sb.append(s"project_new $revision -overwrite\n\n")

    sb.append("# Device\n")
    g("FAMILY", "\"" + fpga.family.quartusFamilyName + "\"")
    g("DEVICE", fpga.name)
    g("TOP_LEVEL_ENTITY", config.entityName)
    g("PROJECT_OUTPUT_DIRECTORY", "output_files")
    sb.append("\n")

    // BOARD properties only. The PART's own properties are deliberately NOT
    // restated: Quartus derives the junction-temperature range and core supply
    // voltage from the ordering code, and EP4CGX150DF27I7's "I" is industrial.
    // Measured 2026-08-24 -- building with and without
    // MIN/MAX_CORE_JUNCTION_TEMP and NOMINAL_CORE_SUPPLY_VOLTAGE analysed the
    // SAME corners either way: Fast 1200mV -40C, Slow 1200mV -40C, Slow 1200mV
    // 100C. Restating them adds a second copy of a fact the part number already
    // carries, which is how a wrong temperature grade would go unnoticed.
    //
    // What Quartus CANNOT know stays here: which I/O voltage the board wires
    // its banks to, and whether the CRC error-check circuitry is wanted.
    sb.append("# Board properties (the part's own come from its ordering code)\n")
    g("STRATIX_DEVICE_IO_STANDARD", "\"3.3-V LVCMOS\"")
    g("ERROR_CHECK_FREQUENCY_DIVISOR", "1")
    sb.append("\n")

    sb.append("# Configuration pins -- this board boots from the JTAG/serial path,\n")
    sb.append("# so the dedicated configuration pins are released as user I/O.\n")
    g("ENABLE_OCT_DONE", "OFF")
    g("ENABLE_CONFIGURATION_PINS", "OFF")
    g("ENABLE_BOOT_SEL_PIN", "OFF")
    g("USE_CONFIGURATION_DEVICE", "OFF")
    g("ACTIVE_SERIAL_CLOCK", "FREQ_40MHZ")
    g("ENABLE_SIGNALTAP", "OFF")
    sb.append("\n")

    sb.append("# I/O timing measurement conventions (Quartus defaults, stated)\n")
    Seq("NEAR_END_VMEAS \"HALF VCCIO\"", "FAR_END_VMEAS \"HALF SIGNAL SWING\"").foreach { m =>
      Seq("-rise", "-fall").foreach(edge => g(s"OUTPUT_IO_TIMING_$m", edge))
    }
    sb.append("\n")

    // Depth is derived from the layout, not assumed: if the structure grows a
    // level these paths follow it.
    val projectDir = layout.quartusDir(preset, buildArgs)
    def up(p: String) = layout.relativeTo(projectDir, p)
    // The LPM ROM/RAM wrappers name their .mif files with a path relative to
    // the OLD project location (`../../asm/generated/serial/rom.mif`), baked
    // into fpga/ip/altera_lpm/*.vhd. Moving the project changed that depth, so
    // the literal no longer resolves and synthesis fails with
    //   Error (127001): Can't find Memory Initialization File ... rom.mif
    // SEARCH_PATH lets Quartus find them by name from wherever the project is,
    // without editing shared IP that other boards still build against.
    sb.append("# Where to find memory initialisation files (see comment in the generator)\n")
    g("SEARCH_PATH", up("asm/generated/serial"))
    g("SEARCH_PATH", up("."))
    sb.append("\n")

    sb.append("# Sources\n")
    g("VERILOG_FILE", up(s"${layout.rtlDir(preset, buildArgs)}/${config.entityName}.v"))
    g("VHDL_FILE", layout.relativeTo(projectDir, layout.ipDir(preset, buildArgs) + "/dram_pll.vhd"))
    // SDR needs the tri-state SDRAM controller; every Altera build needs the
    // LPM ROM/RAM the microcode store is built from.
    if (memType.contains(MemoryType.SDRAM_SDR)) {
      g("VERILOG_FILE", up("fpga/ip/altera_sdram_tri_controller/altera_sdram_tri_controller.v"))
      g("VERILOG_FILE", up("fpga/ip/altera_sdram_tri_controller/efifo_module.v"))
    }
    g("VHDL_FILE", up("fpga/ip/altera_lpm/arom.vhd"))
    g("VHDL_FILE", up("fpga/ip/altera_lpm/aram.vhd"))
    sb.append("\n")

    sb.append("# Timing constraints, generated from the same config (TimingConstraints).\n")
    sb.append("# The clock period comes from the board oscillator and the PLL instance\n")
    sb.append("# name from PllType.instanceName -- the hand-written file named it `pll`\n")
    sb.append("# where the design says `dramPll`, and Quartus discarded every group.\n")
    g("SDC_FILE", s"$revision.sdc")
    sb.append("\n")

    sb.append("# Pin assignments, from the board definition in Board.scala\n")
    sb.append(QsfGenerator.toQsf(QsfGenerator.pinAssignments(config))).append("\n\n")

    sb.append("project_close\n")
    sb.toString
  }
}

/** Write the project-creation Tcl for a preset. */
object QuartusProjectMain extends App {
  import jop.system.JopTopVerilog

  private val writeIdx = args.indexOf("--write")
  private val outPath =
    if (writeIdx >= 0 && args.length > writeIdx + 1) Some(args(writeIdx + 1)) else None
  private val revIdx = args.indexOf("--revision")
  private val revision = if (revIdx >= 0 && args.length > revIdx + 1) args(revIdx + 1) else "jop"
  // Only indices of flags that are actually PRESENT; a missing flag gives
  // index -1, and -1 + 1 = 0 would consume the preset name.
  private val consumed =
    (if (writeIdx >= 0) Set(writeIdx, writeIdx + 1) else Set.empty[Int]) ++
    (if (revIdx   >= 0) Set(revIdx,   revIdx + 1)   else Set.empty[Int])
  private val presetArgs =
    args.zipWithIndex.filterNot { case (_, i) => consumed.contains(i) }.map(_._1)

  val preset = presetArgs.headOption.getOrElse("ep4cgx150Serial")
  val config = JopTopVerilog.resolvePreset(preset, presetArgs)
  val tcl = QuartusProject.generate(config, revision, preset, presetArgs.drop(1).toSeq)

  outPath match {
    case Some(path) =>
      val f = new java.io.File(path)
      Option(f.getParentFile).foreach(_.mkdirs())
      val w = new java.io.PrintWriter(f)
      try w.print(tcl) finally w.close()
      println(s"Wrote $path")
    case None => println(tcl)
  }
}
