package jop.generate

import jop.config._

/** A clock the timing tools must know about: a port, and how fast it runs. */
case class ClockConstraint(port: String, freqHz: BigDecimal, name: Option[String] = None) {
  def clockName: String = name.getOrElse(port)
  def periodNs: BigDecimal =
    (BigDecimal("1000000000") / freqHz).setScale(3, BigDecimal.RoundingMode.HALF_UP)
}

/**
 * The timing intent of a design, held once and rendered per toolchain.
 *
 * WHY THIS EXISTS. The same intent is currently written three ways by hand, and
 * hand-written constraint text rots silently -- four dead constraints were
 * found on 2026-08-23/24 alone, none of which failed a build:
 *
 *   - `source` inside a Vivado .xdc, ignored (item 58), so SDR IOB packing and
 *     the Ethernet GMII constraints had never been applied
 *   - 19 SignalTap VIRTUAL_PIN assignments for ports no longer in the RTL
 *   - `jop_sdram.sdc`'s entire `set_clock_groups`, discarded because it named
 *     the PLL instance `pll` where the design instantiates `dramPll`
 *
 * That last one is why `PllType.instanceName` is now STATED in Scala and read
 * from here, rather than copied into a constraint file where nothing checks it.
 *
 * THREE TOOLCHAINS, THREE RENDERINGS of the same facts:
 *
 *   concept        Altera (.sdc)          Xilinx (.xdc)        ECP5 (.lpf)
 *   clock          create_clock -period   create_clock         FREQUENCY PORT
 *   async groups   set_clock_groups       set_clock_groups     BLOCK ASYNCPATHS
 *   derive         derive_pll_clocks      (implicit)           (implicit)
 *
 * The ECP5 flow is the open-source one (yosys/nextpnr/ecppack) and its .lpf
 * carries pins, I/O attributes and timing in a single file, so its renderer is
 * coarser by nature: nextpnr takes a target frequency and blocks asynchronous
 * paths wholesale rather than naming clock groups.
 */
case class TimingConstraints(
  clocks: Seq[ClockConstraint] = Seq.empty,
  /** Groups of clock names mutually asynchronous to each other. A group with
    * fewer than two entries constrains nothing and is dropped. */
  asyncGroups: Seq[Seq[String]] = Seq.empty,
  /** Altera needs these explicitly; the others infer PLL outputs. */
  derivePllClocks: Boolean = false) {

  def toSdc: String = {
    val sb = new StringBuilder
    sb.append("# Generated by JOP TimingConstraints -- do not hand-edit.\n\n")
    clocks.foreach { c =>
      sb.append(s"create_clock -period ${c.periodNs} -name ${c.clockName} [get_ports ${c.port}]\n")
    }
    if (derivePllClocks) sb.append("\nderive_pll_clocks\nderive_clock_uncertainty\n")
    val groups = asyncGroups.filter(_.nonEmpty)
    if (groups.size >= 2) {
      sb.append("\n# Mutually asynchronous clock domains. The PLL instance name comes\n")
      sb.append("# from PllType.instanceName, not from a hand-copied string.\n")
      sb.append("set_clock_groups -asynchronous \\\n")
      sb.append(groups.map(g => "    -group {" + g.mkString(" ") + "}").mkString(" \\\n"))
      sb.append("\n")
    }
    sb.toString
  }

  def toXdc: String = {
    val sb = new StringBuilder
    sb.append("# Generated by JOP TimingConstraints -- do not hand-edit.\n\n")
    clocks.foreach { c =>
      sb.append(s"create_clock -period ${c.periodNs} -name ${c.clockName} [get_ports {${c.port}}]\n")
    }
    val groups = asyncGroups.filter(_.nonEmpty)
    if (groups.size >= 2) {
      sb.append("\nset_clock_groups -asynchronous \\\n")
      sb.append(groups.map(g =>
        "    -group [get_clocks {" + g.mkString(" ") + "}]").mkString(" \\\n"))
      sb.append("\n")
    }
    sb.toString
  }

  /** ECP5 fragment. Pins and I/O attributes are emitted elsewhere; this is the
    * timing half only, so it is appended to a .lpf rather than being one. */
  def toLpf: String = {
    val sb = new StringBuilder
    sb.append("# Generated by JOP TimingConstraints -- do not hand-edit.\n")
    clocks.foreach { c =>
      val mhz = (c.freqHz / BigDecimal(1000000)).setScale(3, BigDecimal.RoundingMode.HALF_UP)
        .bigDecimal.stripTrailingZeros.toPlainString
      sb.append(s"""FREQUENCY PORT "${c.port}" $mhz MHZ;\n""")
    }
    // nextpnr has no clock-group syntax: asynchronous relationships are blocked
    // wholesale. Stated rather than silently dropped, so the difference from the
    // vendor flows is visible.
    if (asyncGroups.filter(_.nonEmpty).size >= 2)
      sb.append("BLOCK ASYNCPATHS;\nBLOCK RESETPATHS;\n")
    sb.toString
  }
}

object TimingConstraints {

  /** Derive a design's clock constraints from its config. */
  def forConfig(config: JopConfig): TimingConstraints = {
    val assembly = config.assembly
    val board = assembly.fpgaBoard
    val memType = config.resolveMemory(config.system).map(_.memType)

    val boardClock = PinResolver.clockFpgaPin(assembly).map(_ =>
      ClockConstraint("clk_in", assembly.boardClockFreq.toBigDecimal))

    // Which PLL outputs this design actually uses. AlteraDramPll drives the
    // system from c1, and on SDR additionally the SDRAM (c2) and VGA/Eth (c3).
    val pllOutputs =
      if (memType.contains(MemoryType.SDRAM_SDR)) Seq(1, 2, 3) else Seq(1)

    val dramGroup = board.pllType.toSeq.flatMap { pt =>
      if (pt.instanceName.isEmpty) Nil else pllOutputs.map(pt.alteraClockPath)
    }
    // The Ethernet PLL and the PHY's receive clock are separate domains -- but
    // only when the DESIGN instantiates Ethernet, not merely when the board
    // carries the chip. The hand-written jop_sdram.sdc keyed off the board and
    // so named e_rxc on a UART-only build, which Quartus reported as
    //   Warning (332174): Ignored filter ... e_rxc could not be matched with a clock
    // and then discarded the whole set_clock_groups. Constrain what exists.
    val hasEth = config.system.effectiveDevices.values.exists(_.deviceType.key == "eth")
    val ethGroup =
      if (hasEth && board.hasEthPll) Seq("ethPll|altpll_component|auto_generated|pll1|clk[0]") else Nil
    val phyGroup = if (hasEth) Seq("e_rxc") else Nil

    TimingConstraints(
      clocks = boardClock.toSeq,
      asyncGroups = Seq(dramGroup, ethGroup, phyGroup).filter(_.nonEmpty),
      derivePllClocks = config.fpgaFamily.manufacturer == Manufacturer.Altera)
  }
}

/** Print, or write, a design's timing constraints in its toolchain's format. */
object TimingConstraintsMain extends App {
  import jop.system.JopTopVerilog

  private val writeIdx = args.indexOf("--write")
  private val outPath =
    if (writeIdx >= 0 && args.length > writeIdx + 1) Some(args(writeIdx + 1)) else None
  // See XdcGeneratorMain: an absent --write must not filter index 0.
  private val presetArgs =
    if (writeIdx < 0) args
    else args.zipWithIndex.filterNot { case (_, i) => i == writeIdx || i == writeIdx + 1 }.map(_._1)

  val preset = presetArgs.headOption.getOrElse("ep4cgx150Serial")
  val config = JopTopVerilog.resolvePreset(preset, presetArgs)
  val tc = TimingConstraints.forConfig(config)

  val body = config.fpgaFamily.manufacturer match {
    case Manufacturer.Altera  => tc.toSdc
    case Manufacturer.Xilinx  => tc.toXdc
    case _                    => tc.toLpf   // Lattice ECP5, open-source flow
  }

  outPath match {
    case Some(path) =>
      val f = new java.io.File(path)
      Option(f.getParentFile).foreach(_.mkdirs())
      val w = new java.io.PrintWriter(f)
      try w.print(body) finally w.close()
      println(s"Wrote $path")
    case None => println(body)
  }
}
