package jop.generate

import jop.config._

/**
 * Vivado .xdc Constraint File Generator
 *
 * Generates set_property PACKAGE_PIN / IOSTANDARD constraints from JopConfig.
 * Uses PinResolver for shared pin resolution.
 *
 * Xilinx-specific features:
 *   - create_clock for board oscillator
 *   - resetn for default clock domain (active-low)
 *   - IOSTANDARD on every pin
 *   - SDR SDRAM IOB packing (via shared sdram_sdr.xdc)
 *   - CFGBVS / CONFIG_VOLTAGE / BITSTREAM.GENERAL.COMPRESS
 *
 * DDR3 pins are managed by MIG IP and not included here.
 */
object XdcGenerator {

  /** Generate complete XDC constraint file */
  def generate(config: JopConfig): String = {
    val assembly = config.assembly
    val sys = config.system
    val sb = new StringBuilder

    sb.append("# Generated by JOP XdcGenerator\n")
    sb.append(s"# Assembly: ${assembly.name}\n")
    sb.append(s"# System: ${sys.name}\n\n")

    // Clock
    PinResolver.clockFpgaPin(assembly).foreach { pin =>
      val freqHz = assembly.boardClockFreq.toBigDecimal
      val periodNs = (BigDecimal("1000000000") / freqHz)
        .setScale(3, BigDecimal.RoundingMode.HALF_UP)
      sb.append("# System clock\n")
      sb.append(pinConstraint(pin, "clk"))
      sb.append(s"create_clock -period $periodNs -name sys_clk [get_ports {clk}]\n\n")
    }

    // Reset (active-low, from board push button)
    PinResolver.resetFpgaPin(assembly).foreach { pin =>
      sb.append("# Reset (active low)\n")
      sb.append(pinConstraint(pin, "resetn"))
      sb.append("\n")
    }

    // Separate driver pins into UART and others
    val allDriverPins = PinResolver.driverPins(assembly, sys)
    val uartPins = allDriverPins.filter(_.verilogPort.startsWith("ser_"))
    val otherDriverPins = allDriverPins.filterNot(_.verilogPort.startsWith("ser_"))

    // UART
    if (uartPins.nonEmpty) {
      sb.append("# UART\n")
      uartPins.foreach(p => sb.append(pinConstraint(p.fpgaPin, p.verilogPort)))
      sb.append("\n")
    }

    // LEDs
    val leds = PinResolver.ledPins(assembly)
    if (leds.nonEmpty) {
      sb.append("# LEDs\n")
      leds.foreach(p => sb.append(pinConstraint(p.fpgaPin, p.verilogPort)))
      sb.append("\n")
    }

    // SDR SDRAM
    val sdramClk = PinResolver.sdramClockFpgaPin(assembly)
    val sdramPins = PinResolver.sdramPins(assembly)
    if (sdramPins.nonEmpty || sdramClk.isDefined) {
      sb.append("# SDR SDRAM\n")
      sdramClk.foreach(pin => sb.append(pinConstraint(pin, "sdram_clk")))

      // Group SDRAM pins by category for readability
      val ctrl = sdramPins.filter(p => Seq("CKE", "CSn", "RASn", "CASn", "WEn")
        .exists(s => p.verilogPort == s"sdram_$s"))
      val ba = sdramPins.filter(_.verilogPort.startsWith("sdram_BA"))
        .sortBy(_.verilogPort)
      val dqm = sdramPins.filter(_.verilogPort.startsWith("sdram_DQM"))
        .sortBy(_.verilogPort)
      val addr = sdramPins.filter(_.verilogPort.startsWith("sdram_ADDR"))
        .sortBy(p => extractIndex(p.verilogPort))
      val dq = sdramPins.filter(_.verilogPort.startsWith("sdram_DQ["))
        .sortBy(p => extractIndex(p.verilogPort))

      ctrl.foreach(p => sb.append(pinConstraint(p.fpgaPin, p.verilogPort)))
      ba.foreach(p => sb.append(pinConstraint(p.fpgaPin, p.verilogPort)))
      dqm.foreach(p => sb.append(pinConstraint(p.fpgaPin, p.verilogPort)))
      addr.foreach(p => sb.append(pinConstraint(p.fpgaPin, p.verilogPort)))
      dq.foreach(p => sb.append(pinConstraint(p.fpgaPin, p.verilogPort)))

      sb.append("\n# SDR SDRAM IOB packing (include shared constraint file)\n")
      sb.append("# source <path-to>/fpga/constraints/sdram_sdr.xdc\n\n")
    }

    // Other peripheral pins (Ethernet, VGA, SD)
    if (otherDriverPins.nonEmpty) {
      sb.append("# Peripheral pins\n")
      otherDriverPins.foreach(p => sb.append(pinConstraint(p.fpgaPin, p.verilogPort)))
      sb.append("\n")
    }

    // Configuration properties
    sb.append("# Configuration\n")
    sb.append("set_property CFGBVS VCCO [current_design]\n")
    sb.append("set_property CONFIG_VOLTAGE 3.3 [current_design]\n")
    sb.append("set_property BITSTREAM.GENERAL.COMPRESS TRUE [current_design]\n")

    sb.toString
  }

  /** Format PACKAGE_PIN + IOSTANDARD for a single pin */
  private def pinConstraint(fpgaPin: String, port: String,
                            ioStandard: String = "LVCMOS33"): String =
    s"set_property PACKAGE_PIN $fpgaPin [get_ports {$port}]\n" +
    s"set_property IOSTANDARD $ioStandard [get_ports {$port}]\n"

  /** Extract numeric index from a bus port name like "sdram_ADDR[5]" */
  private def extractIndex(port: String): Int =
    port.dropWhile(_ != '[').drop(1).takeWhile(_ != ']').toIntOption.getOrElse(0)
}

/** Print generated XDC for a Xilinx preset */
object XdcGeneratorMain extends App {
  import jop.system.JopTopVerilog
  val preset = args.headOption.getOrElse("wukongSdram")
  val config = JopTopVerilog.resolvePreset(preset, args)
  println(XdcGenerator.generate(config))
}
