package jop.generate

import jop.config._

/**
 * Vivado .xdc Constraint File Generator
 *
 * Generates set_property PACKAGE_PIN / IOSTANDARD constraints from JopConfig.
 * Uses PinResolver for shared pin resolution.
 *
 * Xilinx-specific features:
 *   - create_clock for board oscillator
 *   - resetn for default clock domain (active-low)
 *   - IOSTANDARD on every pin
 *   - SDR SDRAM IOB packing (inlined)
 *   - CFGBVS / CONFIG_VOLTAGE / BITSTREAM.GENERAL.COMPRESS
 *
 * DDR3 pins are managed by MIG IP and not included here.
 */
object XdcGenerator {

  /** Generate complete XDC constraint file */
  def generate(config: JopConfig): String = {
    val assembly = config.assembly
    val sys = config.system
    val sb = new StringBuilder

    sb.append("# Generated by JOP XdcGenerator\n")
    sb.append(s"# Assembly: ${assembly.name}\n")
    sb.append(s"# System: ${sys.name}\n\n")

    // Clock
    PinResolver.clockFpgaPin(assembly).foreach { pin =>
      val freqHz = assembly.boardClockFreq.toBigDecimal
      val periodNs = (BigDecimal("1000000000") / freqHz)
        .setScale(3, BigDecimal.RoundingMode.HALF_UP)
      sb.append("# System clock\n")
      sb.append(pinConstraint(pin, "clk"))
      sb.append(s"create_clock -period $periodNs -name sys_clk [get_ports {clk}]\n\n")
    }

    // Reset, from the same config predicate JopTop and QsfGenerator use, so
    // the port NAME is not restated here (Xilinx "resetn" vs Altera "reset_n").
    config.resetInput.foreach { r =>
      sb.append(s"# Reset (active ${if (r.activeLow) "low" else "high"})\n")
      sb.append(pinConstraint(r.pin, r.port))
      sb.append("\n")
    }

    // Separate device pins into UART and others
    val allDriverPins = PinResolver.devicePins(assembly, sys.effectiveDevices)
    val uartPins = allDriverPins.filter(_.verilogPort.startsWith("ser_"))
    val otherDriverPins = allDriverPins.filterNot(_.verilogPort.startsWith("ser_"))

    // UART
    if (uartPins.nonEmpty) {
      sb.append("# UART\n")
      uartPins.foreach(p => sb.append(pinConstraint(p.fpgaPin, p.verilogPort)))
      sb.append("\n")
    }

    // LEDs
    val leds = PinResolver.ledPins(assembly)
    if (leds.nonEmpty) {
      sb.append("# LEDs\n")
      leds.foreach(p => sb.append(pinConstraint(p.fpgaPin, p.verilogPort)))
      sb.append("\n")
    }

    // SDR SDRAM — only when the SYSTEM uses it, not merely when the board has
    // the chip. The Wukong carries both an SDR part and DDR3, so filtering on
    // the assembly alone emitted 40-odd sdram_* constraints into a DDR3 build
    // for ports that design does not have. Vivado only warns about those, which
    // is worse than failing: the file looks right and the warning scrolls past.
    val usesSdr = config.systems.exists(s =>
      config.resolveMemory(s).exists(_.memType == MemoryType.SDRAM_SDR))
    val sdramClk = if (usesSdr) PinResolver.sdramClockFpgaPin(assembly) else None
    val sdramPins = if (usesSdr) PinResolver.sdramPins(assembly) else Seq.empty
    if (sdramPins.nonEmpty || sdramClk.isDefined) {
      sb.append("# SDR SDRAM\n")
      sdramClk.foreach(pin => sb.append(pinConstraint(pin, "sdram_clk")))

      // Group SDRAM pins by category for readability
      val ctrl = sdramPins.filter(p => Seq("CKE", "CSn", "RASn", "CASn", "WEn")
        .exists(s => p.verilogPort == s"sdram_$s"))
      val ba = sdramPins.filter(_.verilogPort.startsWith("sdram_BA"))
        .sortBy(_.verilogPort)
      val dqm = sdramPins.filter(_.verilogPort.startsWith("sdram_DQM"))
        .sortBy(_.verilogPort)
      val addr = sdramPins.filter(_.verilogPort.startsWith("sdram_ADDR"))
        .sortBy(p => extractIndex(p.verilogPort))
      val dq = sdramPins.filter(_.verilogPort.startsWith("sdram_DQ["))
        .sortBy(p => extractIndex(p.verilogPort))

      ctrl.foreach(p => sb.append(pinConstraint(p.fpgaPin, p.verilogPort)))
      ba.foreach(p => sb.append(pinConstraint(p.fpgaPin, p.verilogPort)))
      dqm.foreach(p => sb.append(pinConstraint(p.fpgaPin, p.verilogPort)))
      addr.foreach(p => sb.append(pinConstraint(p.fpgaPin, p.verilogPort)))
      dq.foreach(p => sb.append(pinConstraint(p.fpgaPin, p.verilogPort)))

      // Inlined rather than `source`d. These are two lines that depend only on
      // signal naming, and a source line would need a path relative to wherever
      // this file is written -- which the generator does not know. It was a
      // COMMENT before now, so a generated file adopted as-is would silently
      // have lost IOB packing. fpga/constraints/sdram_sdr.xdc stays until the
      // SDRAM exerciser flow is generated too; it still sources it.
      sb.append("\n# SDR SDRAM I/O block packing (deterministic timing)\n")
      sb.append("set_property IOB TRUE [get_ports {sdram_DQ[*]}]\n")
      sb.append("set_property IOB TRUE [get_ports {sdram_DQM[*]}]\n\n")
    }

    // Other peripheral pins (Ethernet, VGA, SD)
    if (otherDriverPins.nonEmpty) {
      sb.append("# Peripheral pins\n")
      otherDriverPins.foreach(p => sb.append(pinConstraint(p.fpgaPin, p.verilogPort)))
      sb.append("\n")
    }

    // Configuration properties
    sb.append("# Configuration\n")
    sb.append("set_property CFGBVS VCCO [current_design]\n")
    sb.append("set_property CONFIG_VOLTAGE 3.3 [current_design]\n")
    sb.append("set_property BITSTREAM.GENERAL.COMPRESS TRUE [current_design]\n")

    sb.toString
  }

  /** Format PACKAGE_PIN + IOSTANDARD for a single pin */
  private def pinConstraint(fpgaPin: String, port: String,
                            ioStandard: String = "LVCMOS33"): String =
    s"set_property PACKAGE_PIN $fpgaPin [get_ports {$port}]\n" +
    s"set_property IOSTANDARD $ioStandard [get_ports {$port}]\n"

  /** Extract numeric index from a bus port name like "sdram_ADDR[5]" */
  private def extractIndex(port: String): Int =
    port.dropWhile(_ != '[').drop(1).takeWhile(_ != ']').toIntOption.getOrElse(0)
}

/** Print, or write, the generated XDC for a Xilinx preset.
  *
  * `--write <path>` follows ConstGeneratorMain, which has emitted Const.java
  * into the Java build for as long as anyone has been running it -- the same
  * shape: config in, generated artefact out, consumed downstream, staleness
  * handled by make.
  *
  * Writing under spinalhdl/generated/ deliberately, alongside the Verilog: that
  * directory is already gitignored as build output, which is where generated
  * constraints belong if fpga/ is ever to stop being tracked by hand.
  */
object XdcGeneratorMain extends App {
  import jop.system.JopTopVerilog

  private val writeFlag = args.indexOf("--write")
  private val outPath =
    if (writeFlag >= 0 && args.length > writeFlag + 1) Some(args(writeFlag + 1)) else None
  private val presetArgs =
    args.zipWithIndex.filterNot { case (_, i) => i == writeFlag || i == writeFlag + 1 }.map(_._1)

  val preset = presetArgs.headOption.getOrElse("wukongSdram")
  val config = JopTopVerilog.resolvePreset(preset, presetArgs)
  val xdc = XdcGenerator.generate(config)

  outPath match {
    case Some(path) =>
      val f = new java.io.File(path)
      Option(f.getParentFile).foreach(_.mkdirs())
      val w = new java.io.PrintWriter(f)
      try w.print(xdc) finally w.close()
      println(s"Wrote $path")
    case None => println(xdc)
  }
}
